### ISSUE TITLE
-Si option returns errors

### ISSUE THREAD

**Issue by smirkybg** [archlinuxfr/yaourt#101]
Steps to reproduce:
yaourt -Si <aur_package>

Example:
$ yaourt -Si yaourt
/dev/fd/63: line 11: syntax error near unexpected token `('
/dev/fd/63: line 11: `declare optdepends=('aurvote: vote for favorite packages from AUR'       'customizepkg: automatically modify PKGBUILD during install/upgrade'       'rsync: retrieve PKGBUILD from official repositories')'
Repository     : aur
Name           : yaourt
Version        : 1.5-1
URL            : https://github.com/archlinuxfr/yaourt
AUR URL        : https://aur.archlinux.org/packages/yaourt
Licenses       : GPL
Votes          : 2599
Out Of Date    : No
Groups         : None
Provides       : None
Depends On     : diffutils pacman>=4.1 package-query>=1.4 gettext
Optional Deps  : None
Conflicts With : None
Replaces       : None
Maintainer     : archlinuxfr
Architecture   : any
Last update    : Mon 23 Jun 2014 01:44:42 PM EEST
Description    : A pacman wrapper with extended features and AUR support

This happens with every AUR package. The official repos don't have such problems.

**Comment by Skunnyk** [comment]
Please test with the git version of yaourt, https://github.com/archlinuxfr/yaourt/pull/88 has fixed this problem.

**Comment by smirkybg** [comment]
Yes, it's working as expected with yaourt-git.
I just saw that the last "Release" is from Jun 23, 2014. Are you planning to dump a new one in the near future?

**Comment by Skunnyk** [comment]
Yup, I will try to release a new version soon :)

**Comment by Skunnyk** [comment]
Yup, I will try to release a new version soon :)
