### ISSUE TITLE
Add a --confirm/--edit option

### ISSUE THREAD

**Issue by dreuter** [archlinuxfr/yaourt#106]
Hi,

I recently added `NOCONFIRM=1` and `EDITFILES=0` to my yaourtrc. Then I discovered, that the chrome pepper package had wrong checksums. I was not able to fix this until I moved my yaourtrc to another place, to use the system wide one.

Could you please add a --confirm/--edit (I am not sure if thats the best name) option, so that one can optionally edit the files, without changing his/her config?

Or was I just missing that option?

PS: I know that these settings are considered dangerous, but I do not read most of the PKGBUILDs anyways... I was just annoyed of typing --noconfirm all the time,

**Comment by f2404** [comment]
usage:  pacman {-S --sync} [options] [package(s)]
      --confirm        always ask for confirmation

Isn't it what you're looking for?

**Comment by spacekookie** [comment]
Hi, I just recently added the `EDITFILES=0` to my yaourtrc and the `--confirm` option doesn't help. I want to edit the PKGBUILD, not confirm the build.

**Comment by larchunix** [comment]
Done:

* `--confirm` => #235
* `--edit` => #278
