### ISSUE TITLE
Allow to skip validity checks

### ISSUE THREAD

**Issue by qubodup** [archlinuxfr/yaourt#108]
Please allow to pass

       --skipinteg
           Do not perform any integrity checks (checksum and PGP)
           on source files.

       --skipchecksums
           Do not verify checksums of source files.

       --skippgpcheck
           Do not verify PGP signatures of source files.

For makepkg, so it is easier to build different versions without us having to get the checksums somehow.

**Comment by larchunix** [comment]
Using yaourt git version, you can set the variable MAKEPKG (in your environment or in your yaourtrc file) to add custom options to makepkg (d6203ee).
 
    export MAKEPKG="makepkg --skipinteg"
    yaourt -Sb package

**Comment by basinilya** [comment]
yaourt -m,--makepkg-option would be easier to type

**Comment by larchunix** [comment]
A similar option exists since yaourt-1.4 (although it is not documented).
See commit cb448d4 which added the --m-arg option.

    yaourt --m-arg "--skipchecksums --skippgpcheck" -Sb package

**Comment by erm3nda** [comment]
@larchunix, the `yaourt --m-arg "--skipchecksums --skippgpcheck" -Sb package` did not workeed on my case. Complained with `makepkg: la opción no es válida '--skipchecksums --skippgpcheck'`. I used only the `--skippgpcheck` option like `yaourt --m-arg " --skippgpcheck" -Sb package` and worked. Now i wonder how should i pass both parameters if anytime the buildpkg fails at both steps... cuz i was lucky and the md5sum was ok. Tank you very much for pointing out that option :D

**Comment by larchunix** [comment]
@erm3nda, I just pushed a commit fixing this issue (b78aab5).

Until a new release including this fix is out, you should be able to pass multiple options to `makepkg` by using `--m-arg` as much time as needed, i.e:

```
yaourt --m-arg --skipchecksums --m-arg --skippgpcheck -Sb package
```

**Comment by erm3nda** [comment]
Ok. I see the example had --m-arg "with quoted options", so maybe that is what produces the error. Thank you.
