### ISSUE TITLE
Breakage with zsh when doing Ctrl+C

### ISSUE THREAD

**Issue by jleclanche** [archlinuxfr/yaourt#11]
Since recently, in zsh, doing yaourt -Su followed by Ctrl+C at the "Continue upgrade ? [Y/n]" prompt results in shell breakage; password prompts no longer work properly for example.

This doesn't happen on bash. I haven't tested in yaourt-git yet.

**Comment by xuhdev** [comment]
I have the same problem with zsh.

**Comment by jlovison** [comment]
I've had the same issue with zsh -- just in case anyone stumbles across this issue before it gets fixed, a temporary solution is using `Ctrl+D` to send an EOF to the terminal -- works fine for both sudo password entry and `[Y/n]` confirm prompts.
