### ISSUE TITLE
versons are reported as (null)

### ISSUE THREAD

**Issue by gaydenko** [archlinuxfr/yaourt#116]
Hi!

I guess the issue has appeared after last yaourt/package-query update: -Qm reports all local packaages' versions as `(null)`:
```
...
local/urxvt-vtwheel (null)
local/wrk (null)
local/xkb-switch-git (null)
local/yaourt (null)
```
While `packman -Qm` reports correct versions.

A system is up to date
```
$ pacman -Qm yaourt package-query
yaourt 1.6-1
package-query 1.6.1-1
```

**Comment by gaydenko** [comment]
Just want to add, the issue doesn't depend on the concrete Arch system as far the the issue takes place on the other (maintained by me) Arch workstation also.

**Comment by Skunnyk** [comment]
Yep, can reproduce, it's a bug in package-query (introduced by https://github.com/archlinuxfr/package-query/commit/d42d69f8c2473453e192bb92e135173e820e7ea2 / https://github.com/archlinuxfr/package-query/commit/3a0a9211d4aaa1d57ba42f936d26699629f7664a ).

I have a fix, can you try package-query-git ?

**Comment by gaydenko** [comment]
@Skunnyk , yes, `package-query-git` shows versions as expected:
```
$ yaourt -Qm package-query-git 
local/package-query-git 1.6.1.1.g8724261-1
```

**Comment by gaydenko** [comment]
@Skunnyk , I'm not usre close the issue or not. The issue is related to `package-query`, that is another package, and is fixed in master. OTOH that package isn't updated in AUR yet.

**Comment by Skunnyk** [comment]
Yes, it's related to package-query, and yes, I need to release 1.6.2 ! (I'll try today)

**Comment by gaydenko** [comment]
OK, closing, thanks.
