### ISSUE TITLE
Unable to update AUR4 packages

### ISSUE THREAD

**Issue by marhkb** [archlinuxfr/yaourt#120]
Cannot update AUR4 packages.

Output:
marcus@U530 ~ % LANG=C yaourt -Syua --aur-url "https://aur4.archlinux.org"
:: Synchronizing package databases...
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib-testing is up to date
 multilib is up to date
 pipelight is up to date
 infinality-bundle is up to date
 infinality-bundle-multilib is up to date
 infinality-bundle-fonts is up to date
 kde-thumbnailer-apk : Orphan 
 libappindicator-gtk2 : Orphan 
 libappindicator-gtk3 : Orphan 
 libappindicator-sharp : Orphan 
 Foreign packages: - 126 / 126

==> Package upgrade only (new release):
aur/filezilla-faenza-icons                  0.1-4                  4 -> 5

==> Software upgrade (new version) :
aur/blockify                                1.8.6-1                -> 1.8.7-1
aur/eclipse-subversive                      2.0.4.I20150123_1700-1 -> 3.0.0.I20150529_1700-1
aur/eclipse-subversive-svn-connector        4.1.3.I20150214_1700-1 -> 5.0.0.I20150529_1700-1
aur/eclipse-subversive-svn-connector-svnkit 4.1.3.I20150214_1700-1 -> 5.0.0.I20150529_1700-1
aur/iucode-tool                             1.2.1-1                -> 1.3-1

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> 
:: Starting full system upgrade...
 there is nothing to do

==> Downloading blockify PKGBUILD from AUR...
==> ERROR: blockify not found in AUR.
==> ERROR: unable to update

==> Downloading eclipse-subversive PKGBUILD from AUR...
==> ERROR: eclipse-subversive not found in AUR.
==> ERROR: unable to update

==> Downloading eclipse-subversive-svn-connector PKGBUILD from AUR...
==> ERROR: eclipse-subversive-svn-connector not found in AUR.
==> ERROR: unable to update

==> Downloading eclipse-subversive-svn-connector-svnkit PKGBUILD from AUR...
==> ERROR: eclipse-subversive-svn-connector-svnkit not found in AUR.
==> ERROR: unable to update

==> Downloading filezilla-faenza-icons PKGBUILD from AUR...
==> ERROR: filezilla-faenza-icons not found in AUR.
==> ERROR: unable to update

==> Downloading iucode-tool PKGBUILD from AUR...
==> ERROR: iucode-tool not found in AUR.
==> ERROR: unable to update

**Comment by Skunnyk** [comment]
Yes, it's a bug in package-query , see https://github.com/archlinuxfr/package-query/issues/8 (update of AUR4 rpc api which broke package-query 1.6.1)

**Comment by Skunnyk** [comment]
1.6.2 released
