### ISSUE TITLE
PKGBUILD source: local files, no http

### ISSUE THREAD

**Issue by milahu** [archlinuxfr/yaourt#123]
this might be a makepkg issue, rather than yaourt, but...

i ran into this problem compiling ffmpeg-full with
$ yaourt -S ffmpeg-full

at package decklink-sdk ( https://aur.archlinux.org/packages/decklink-sdk/ ),
i got the error:
==> Retrieving sources...
==> ERROR: Unknown download protocol: file
Aborting...
==> ERROR: Makepkg was unable to build decklink-sdk.

the original PKGBUILD file says:
pkgver=10.4
source=("file://Blackmagic_DeckLink_SDK_${pkgver}.zip")
sha256sums=('901553ad31d4270dc0741797fcffec653e7c82f5e7c62499c060c48437a66bef')

there is no direct http URL for $source like
http://software.blackmagicdesign.com/SDK/Blackmagic_DeckLink_SDK_${pkgver}.zip
which works with pkgver=10.3:
http://software.blackmagicdesign.com/SDK/Blackmagic_DeckLink_SDK_10.3.zip
because you have to visit
https://www.blackmagicdesign.com/support/family/capture-and-playback
and register with your full address,
so you can download the source zip file.

then you would run
$ yaourt -S decklink-sdk
wait for 'edit PKGBUILD?',
edit your PKGBUILD file in
/tmp/yaourt-tmp-$USER/aur-decklink-sdk/PKGBUILD
to something like
source=("file:///home/$USER/Downloads/Blackmagic_DeckLink_SDK_${pkgver}.zip")
or
source=("/home/$USER/Downloads/Blackmagic_DeckLink_SDK_${pkgver}.zip")
to match your downloaded zip file.
then you would proceed with yaourt or makepkg...

----

now the question is:
how can we bring yaourt (or makepkg) to support local source files?

ideally, we would add support for the file protocol
to support file:///home/$USER/... like URLs.

it also would be nice to add support for this kind of source file downloading:
display the registration + download URL
and wait for the local file path...
maybe suggest something like
file:///home/$USER/Downloads/Blackmagic_DeckLink_SDK_${pkgver}.zip

or just add support for the file protocol
and do the rest via the PKGBUILD file...
good documentation is important here.

maybe also add the possibility to downgrade
back to version 10.3,
where you dont need registration,
to download source files...

personally, i dont like filling a registration form
just to be allowed to use a piece of (open source) software... 👎

whatever,
best wishes,
milahu :)

**Comment by Skunnyk** [comment]
You should use local:// and not file:// 
Downloading this kind of tarball is a manual operation
You can look at humblebundle packages ( for example https://aur.archlinux.org/packages/am/amnesia-tdd-hib/PKGBUILD ) which use a custom download wrapper (hib-dlagent).

**Comment by SpiritAbsolute** [comment]
local://home/spiritabsolute/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
local:///home/spiritabsolute/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
it doesn`t work :(

**Comment by f2404** [comment]
@SpiritAbsolute Does `makepkg` build the package successfully?

**Comment by SpiritAbsolute** [comment]
I want install oracle package https://aur.archlinux.org/packages/oracle-xe/
how do I install it?
I downloaded the file oracle-xe-11.2.0-1.0.x86_64.rpm.zip
How to specify it in the source PKGBUILD?

**Comment by f2404** [comment]
Ah, I see your problem. Let me try to build it here.

**Comment by f2404** [comment]
Yeah, I'm getting an error. May be that a wrong path is passed to `makepkg`... Looks like a bug.
```
==> Retrieving sources...
==> ERROR: oracle-xe-11.2.0-1.0.x86_64.rpm.zip was not found in the build directory and is not a URL.
==> ERROR: Makepkg was unable to build oracle-xe.
```

**Comment by kbrownlees** [comment]
This does seem like a bug because yaourt copies things to a build directory in /tmp/ then runs makepkg in there. For me it doesn't pick up local sources so never copies them and makepkg can't find them.

```
==> Copying files from /home/kieran/work/makepkg/linux-lqx to build directory...
'/home/kieran/work/makepkg/linux-lqx/PKGBUILD' -> '/tmp/yaourt-tmp-kieran/aur-linux-lqx/PKGBUILD'
'/home/kieran/work/makepkg/linux-lqx/linux-lqx.install' -> '/tmp/yaourt-tmp-kieran/aur-linux-lqx/linux-lqx.install'
```
```
==> Building and installing package
==> Making package: linux-lqx 4.5.2-1 (Fri Apr 22 10:43:01 NZST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> ERROR: linux-lqx.preset was not found in the build directory and is not a URL.
```

Using just makepkg:

```
$> makepkg
==> Making package: linux-lqx 4.5.2-1 (Fri Apr 22 10:45:17 NZST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux-lqx.preset
```

**Comment by mirh** [comment]
Can confirm this also happens with mathematica package. 
I have to manually copy the installer to temp folder before installation can proceed.
