### ISSUE TITLE
feature request: use `git clone --depth` for AUR git packages

### ISSUE THREAD

**Issue by c-cube** [archlinuxfr/yaourt#125]
It would be nice if the `--depth` option was used for large repositories with a long history, so as to only clone the latest revision; older commits are usually not used for building a package.

**Comment by skogler** [comment]
Currently having the same problem with a project I am packaging, which is only about 26Mb but the repo has over 500Mb with all the history.
I do think that this feature request needs to be in makepkg though, not in yaourt.

**Comment by kokizzu** [comment]
someone has already made the patch, but it's rejected..

https://bugs.archlinux.org/task/23065

**Comment by kokizzu** [comment]
and a long discussion about it https://lists.archlinux.org/pipermail/aur-general/2013-April/022938.html

**Comment by Skunnyk** [comment]
Yes, it's a makepkg "feature", and yaourt use makepkg to build PKGBUILD. So I doubt that we can fix it in yaourt :) Thank you for the link about the discussion
