### ISSUE TITLE
'yaourt -C' does not respect DIFFEDITCMD

### ISSUE THREAD

**Issue by jck** [archlinuxfr/yaourt#127]
I have defined DIFFEDITCMD in ~/.config/yaourt/yaourtrc
The DIFFEDITCMD is not respected by 'yaourt -C' but it is respected by pacdiffviewer

**Comment by Skunnyk** [comment]
Hm, the DIFFEDITCMD is run in sudo mode to be able to write in system files, so it looks like it read the root yaourtrc.
As a workaround you can change the DIFFEDITCMD in /etc/yaourtrc or /root/.config/yaourt/yaourtrc file.
I'll look at it later.
