### ISSUE TITLE
Anaconda Python distribution breaks AUR lookup

### ISSUE THREAD

**Issue by chendaniely** [archlinuxfr/yaourt#128]
Same issue as: https://github.com/rmarquis/pacaur/issues/345

Not sure if this is a common problem in yaourt and pacaur, or from something upstream

**Comment by Skunnyk** [comment]
Anaconda seems to override PATH, and add a custom curl binary in it path which break yaourt/package-query (see https://github.com/archlinuxfr/yaourt/issues/22 / https://github.com/archlinuxfr/yaourt/issues/86 too )

**Comment by rmarquis** [comment]
According to yaourt reported issues, it seems anaconda provides its own version of curl and that one has troubles using https.

You can try removing anaconda's curl with ```conda remove curl```. Closing now.
