### ISSUE TITLE
Clone git repository for -G

### ISSUE THREAD

**Issue by yan12125** [archlinuxfr/yaourt#129]
Current ```-G``` (```--getpkgbuild```) downloads the package tarball and extracts it. For AUR4, it would be great to clone the git repository instead, as it provides a better trace of changed files.

In src/lib/aur.sh, ```aur_get_pkgbuild``` invokes ```package-query -Aif "%u"```. Seems git repository URL is not directly supported in package-query, so I have a relevant post at archlinuxfr/package-query#11

**Comment by Skunnyk** [comment]
Now that package-query have a preliminary support  of git urls ( see https://github.com/archlinuxfr/package-query/commit/5fbcfca9799e529db20dd04bbfcc4103db0b2216 ), we can try to implement git clone package instead of download tarball.

**Comment by Manouchehri** [comment]
Agreed, I always find myself using `git clone` instead of `yaourt -G` now.

**Comment by Skunnyk** [comment]
Implemented in #142
