### ISSUE TITLE
Fail to install when /opt is a symbolic link

### ISSUE THREAD

**Issue by noh4ck** [archlinuxfr/yaourt#136]
I don't know if this is strictly a yaourt issue or not, but when the /opt directory is a symlink to another directory (I do this because of space issues in root) I get this:
```
error: failed to commit transaction (conflicting files)
gitter: /opt exists in filesystem
```

This happens for all packages that wants to install to /opt when opt is a symlink. Changing the symlink to a folder again resolves the issue.

**Comment by Skunnyk** [comment]
This is due to pacman, not yaourt, see the "Directory Symlink Handling" section in http://allanmcrae.com/2014/12/pacman-4-2-released/
