### ISSUE TITLE
Always getting time out when installing packet tracer ver 6.2.2

### ISSUE THREAD

**Issue by rvu95** [archlinuxfr/yaourt#139]
I'm trying to install packet tracer version 6.2.2 from the aur but always getting timeout (unable to download the Cisco Packet Tracer 6.2 for Linux - Ubuntu installation - Student version.tar.gz. So the proccess always stopped here. Any idea? Thanks in advance.

**Comment by Skunnyk** [comment]
The 'source' variable is wrong : 
source=(  http://Cisco Packet Tracer 6.2 for Linux - Ubuntu installation - Student version.tar.gz )

Please ask the maintainer, it's not a yaourt problem :)

**Comment by rvu95** [comment]
where i should ask the maintainer?
