### ISSUE TITLE
Installing using dash/stdin as a parameter doesn't work

### ISSUE THREAD

**Issue by bricewge** [archlinuxfr/yaourt#140]
Installing a package from the official repository or AUR using dash/stdin as a parameter doesn't work:

    # Package from official repository
    $ echo youtube-dl | yaourt -S -
    error: you cannot perform this operation unless you are root.
    $ echo youtube-dl | sudo pacman -S -
    # Package from AUR
    $ echo youtube-dl-git | yaourt -S -
    error: target not found: youtube-dl-git
    $ echo youtube-dl | sudo pacman -S -
    error: target not found: youtube-dl-git

It looks like when giving a dash/stdin parameter `yaourt` directly use pacman and don't even bother to check if it's available in AUR. However this workaround work `yaourt -S $(echo youtube-dl-git)`.

Note that I stumbuled upon this bug when trying to reinstall an AUR package with all of his dependencies with `pactree -u youtube-dl-git -d 1 | yaourt -S -` that I finally substituted for `yaourt -S $(pactree -u
youtube-dl-git -d 1)`.

**Comment by f2404** [comment]
@bricewge Could you verify the patch?

**Comment by bricewge** [comment]
Thanks @f2404, your patch fix the issue!

**Comment by aureooms** [comment]
This issue seems to be back, same symptoms.

    $ yaourt --version
    yaourt 1.9
    homepage: http://archlinux.fr/yaourt-en

**Comment by f2404** [comment]
Seems to work for me with the git version.
What command isn't working for you?

**Comment by aureooms** [comment]
$ yaourt --version                                                                                                                                                                     
    yaourt 1.9
    homepage: http://archlinux.fr/yaourt-en

    $ echo memoize | yaourt -S -                                                                                                                                                       
    error: target not found: memoize

    $ yaourt -S memoize                                                                                                                                                                

    ==> Downloading memoize PKGBUILD from AUR...
    x .SRCINFO
    x PKGBUILD
    memoize 1.0.1-1  (2017-04-10 17:23)
