### ISSUE TITLE
'yaourt -Qu --color' shows old version instead of new version

### ISSUE THREAD

**Issue by simonzack** [archlinuxfr/yaourt#144]
I'm getting the following after running this:

    extra/git 2.5.1-1 -> 2.5.1-1

This is on yaourt 1.6-1. But `yaourt -Syu` gives the correct versions.

**Comment by Skunnyk** [comment]
It's a package-query bug : https://github.com/archlinuxfr/package-query/issues/10 
I need to look at it :)

**Comment by Skunnyk** [comment]
Fixef by https://github.com/archlinuxfr/package-query/issues/19

**Comment by simonzack** [comment]
Thanks, works now!
