### ISSUE TITLE
Segmentation fault on "yaourt arg uml"

### ISSUE THREAD

**Issue by skogshjort** [archlinuxfr/yaourt#145]
`yaourt arg uml`, `yaourt argo um` etc gives a segmentation fault.

Output example:

```
/usr/lib/yaourt/util.sh: line 166:  2645 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"
```

Expected: A search for packages matching both "arg" and "uml".

Happy coding :)

**Comment by Skunnyk** [comment]
Should be fixed in package-query-git : https://github.com/archlinuxfr/package-query/issues/13
Can you try please?

**Comment by skogshjort** [comment]
Yup! Works like a charm :)
