### ISSUE TITLE
util.sh segfault when ›python‹ or ›python2‹ is first element of search query

### ISSUE THREAD

**Issue by Optiligence** [archlinuxfr/yaourt#146]
When supplying several search terms, if the first is `python` or `python2` i.e.
`yaourt python bar` after an incomplete list (less result than web search), there is this output: 
```
/usr/lib/yaourt/util.sh: line 166:  4791 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"
```

**Comment by Skunnyk** [comment]
Yup, fixed in package-query-git, I need to do a release :)
see https://github.com/archlinuxfr/package-query/issues/13

**Comment by MaxKh** [comment]
Please check that the following will be fixed as well

↪ ya -Ss be qqq
/usr/lib/yaourt/util.sh: line 166:  5560 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"

PS: I tried to find "be shell" but found that all "be <smth>" requests cause the issue

**Comment by f2404** [comment]
Shouldn't this one be closed? The issue seems to be resolved.

**Comment by Optiligence** [comment]
yep
