### ISSUE TITLE
target not found!

### ISSUE THREAD

**Issue by mmrezaie** [archlinuxfr/yaourt#147]
I have attached part of the debug I get with yaourt. I am always getting this error past couple of days. I have installed the latest yaourt from aur.

+ pacman_parse -Sp --print-format '## %n' --noconfirm -u pacaur-git
+ LC_ALL=C
+ pacman --color never -Sp --print-format '## %n' --noconfirm -u pacaur-git
error: target not found: pacaur-git
+ REFRESH=0
+ DETAILUPGRADE=0
+ ((  ! DETAILUPGRADE  ))
+ ((  REFRESH  ))
+ ((  REFRESH>1  ))
+ su_pacman -S -u pacaur-git
+ pacman_queue
+ [[ -f /var/lib/pacman//db.lck ]]
+ launch_with_su pacman --color auto -S -u pacaur-git
+ is_sudo_allowed pacman --color auto -S -u pacaur-git
+ ((  SUDOINSTALLED  ))
+ ((  SUDONOVERIF  ))
+ ((  SUDOREDIRECT  ))
+ _is_sudo_allowed pacman --color auto -S -u pacaur-git
+ return 0
+ sudo pacman --color auto -S -u pacaur-git
error: target not found: pacaur-git
+ return 1
+ (( DEVEL ))
+ analyse_status_list
+ (( SHOWORPHANS ))
+ local neworphans
++ LC_ALL=C
++ comm -13 /tmp/yaourt-tmp-mrez/orphans.15884 /dev/fd/63
+++ pkgquery -Qdtf %n --sort n
+++ package-query --aur-url https://aur.archlinux.org -Qdtf %n --sort n
+ neworphans=
+ [[ -n '' ]]
+ [[ ! -n 0 ]]
+ (( AUTOSAVEBACKUPFILE ))
+ return
+ cleanup
+ local line
+ for line in '"${CLEANUP[@]}"'
+ eval echo -ne '\\033\[0m'
++ echo -ne '\033[0m'
+ for line in '"${CLEANUP[@]}"'
+ eval echo -ne '\\033\]0\;xterm-256color\\007'
++ echo -ne '\033]0;xterm-256color\007'
+ for line in '"${CLEANUP[@]}"'
+ eval rm /tmp/yaourt-tmp-mrez/orphans.15884
++ rm /tmp/yaourt-tmp-mrez/orphans.15884

**Comment by Skunnyk** [comment]
What is the yaourt command you run ? 
If AUR/network is unavailable when you run yaourt -S aur-package, you can have this error message.

**Comment by mmrezaie** [comment]
Something like: yaourt -Syu --noconfirm

**Comment by HelgeS** [comment]
I have a similar problem, but I definitely have network access and aur is available as well.
Yaourt is the latest version (1.7) from AUR.

```
$ LC_ALL=C yaourt codelite
1 aur/codelite 8.1-1 (109)
    Open-source, cross platform IDE for the C/C++ programming languages
2 aur/codelite-bin 8.1-2 (17)
    Open-source, cross platform IDE for the C/C++ programming languages
3 aur/codelite-git 8.0.1.r162.g36ea786-1 (10)
    Open-source, cross platform IDE for the C/C++ programming languages
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> --------------------------------------------------------
==> 1


==> Downloading codelite PKGBUILD from AUR...
==> ERROR: codelite not found in AUR.
```

**Comment by f2404** [comment]
HelgeS, your command works fine for me:

$ yaourt codelite
1 aur/codelite 8.1-1 (109)
    Open-source, cross platform IDE for the C/C++ programming languages
2 aur/codelite-bin 8.1-2 (17)
    Open-source, cross platform IDE for the C/C++ programming languages
3 aur/codelite-git 8.0.1.r162.g36ea786-1 (10)
    Open-source, cross platform IDE for the C/C++ programming languages
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 1


==> Downloading codelite PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD

**Comment by mmrezaie** [comment]
Maybe it is because of the latest update but now it is working properly. Sorry for the late reply.
