### ISSUE TITLE
yaourt doesn't respect --noconfirm

### ISSUE THREAD

**Issue by berbigou** [archlinuxfr/yaourt#150]
Hello,
this is my first contribution, please be kind..
*********
resume : yaourt doesn't respect --noconfirm
**********
problem:
sudo pacman -U --noconfirm mypkg.pkg.tar.xz   doesn't stop to ask confirmation and update
yaourt -U --noconfirm mypkg.pkg.tar.xz              stops and asks
**********
system: uname -a
Linux port-ber-linux 4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux

pacman -V
 .--.                  Pacman v4.2.1 - libalpm v9.0.1
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2014 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'

yaourt -V
yaourt 1.6
accueil : http://archlinux.fr/yaourt
***********

I know --noconfirm can be unsafe, this is my own modified webcam driver compiled personnaly.
I want to use --noconfirm in my script, and I would love to use yaourt for that...

Note: my yaourt is in French
I hope this will help.

**Comment by Skunnyk** [comment]
Thank you for your first bug report ;)
Hm, yep, yaourt seems to not respect --noconfirm with -U . Need to look at it.

**Comment by puckel** [comment]
Hi @berbigou,

Did you try to set to "1" the value of "PU_NOCONFIRM" in your /etc/yaourtrc.in ?

**Comment by berbigou** [comment]
Hi @puckel ,
Note: my yaourt has updated to 1.7

I tried both PU_NOCONFIRM=1 and 0 in both /etc/yaourtrc and ~/.yaourtrc ( 4 tests leaving the other file with the default commented line).
same problem noted.

thanks

**Comment by berbigou** [comment]
oups I closed by mistake.
sorry

**Comment by olejon** [comment]
Same here.

**Comment by Skunnyk** [comment]
Fixed by #166

**Comment by olejon** [comment]
Not in AUR yet?

**Comment by con-f-use** [comment]
Still doesn't seem to honor it.
