### ISSUE TITLE
Segmentation fault when 'pkg' with extra text is provided as query

### ISSUE THREAD

**Issue by dsmorozov** [archlinuxfr/yaourt#152]
$ yaourt --version
yaourt 1.6
homepage: http://archlinux.fr/yaourt-en

$ yaourt pkg test
/usr/lib/yaourt/util.sh: line 166:  4899 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"

$ yaourt pkg select
/usr/lib/yaourt/util.sh: line 166:  4951 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"

**Comment by dsmorozov** [comment]
Is this actually a package-query issue?

**Comment by The-Compiler** [comment]
Seems like the same as #133, #146 and https://github.com/archlinuxfr/package-query/issues/13 :wink:

It was fixed in https://github.com/archlinuxfr/package-query/pull/14

> Yup, fixed in package-query-git, I need to do a release :)
-- @Skunnyk :wink:

**Comment by Skunnyk** [comment]
Yes, I need to do a release !
