### ISSUE TITLE
"AUR error : Invalid query arguments" on every single yaourt action.

### ISSUE THREAD

**Issue by FredBezies** [archlinuxfr/yaourt#153]
Hello.

Strange bug which appears today. When I try to do a yaourt -Syua, I got this : 

````[fred@fredo-arch ~]$ yaourt -Syua````
````Mot de passe [sudo] de fred :````
````:: Synchronisation des bases de données de paquets...````
 ````testing est à jour````
 ````core est à jour````
 ````extra est à jour````
```` community-testing est à jour````
 ````community est à jour````
````AUR error : Invalid query arguments````
 ````Paquets étrangers : - 18 / 18````

It happens with both yaourt and yaourt-git. Any idea ? 

And when I try to grab an AUR package to build it locally : 

````[fred@fredo-arch ~]$ yaourt -G yaourt-git````
````AUR error : Invalid query arguments````

Any ideas to fix this ? Thanks for your answer.

**Comment by alphazo** [comment]
I'm getting the same error since I have upgraded my Archlinux system. I even get an additional message after the "Invalid query arguments" one when I try for example to install something from AUR:
   
     error: database not found: aur

**Comment by FredBezies** [comment]
Seems to be related - more or less - to a new aur version.

See this mail from aur-general mailing list : 

https://lists.archlinux.org/pipermail/aur-general/2015-October/031580.html

Anyway, it is really annoying. I installed packer in order to grab AUR packages until yaourt is fixed.

**Comment by alienscience** [comment]
+1 I also get this error after upgrading.

**Comment by maxis11** [comment]
+1
$ yaourt -V
yaourt 1.6

**Comment by kraluk** [comment]
+1
And I get this message.

**Comment by benboit** [comment]
+1
Getting this error in a freshly setup system :(

**Comment by Skunnyk** [comment]
Hm, it's a bug with AUR4.1 and package-query.
It seems that json response on https://aur.archlinux.org/rpc.php has changed. Need to dig it.

**Comment by FredBezies** [comment]
At least, you have a clue :D

**Comment by pounard** [comment]
Same error here.

**Comment by antifriz** [comment]
+1

**Comment by fguerout** [comment]
+1

**Comment by Skunnyk** [comment]
It's a bug on AUR4.1 side (multiinfo call), please wait for the patch to be released in production ! https://lists.archlinux.org/pipermail/aur-dev/2015-October/003793.html / https://bugs.archlinux.org/task/46547?project=2

**Comment by pounard** [comment]
@Skunnyk Thanks a lot for your quick feedbak !

**Comment by Skunnyk** [comment]
Seems fixed ! Thank to Lukas Fleischer !

**Comment by Skunnyk** [comment]
https://lists.archlinux.org/pipermail/aur-general/2015-October/031582.html

**Comment by pounard** [comment]
It works.

**Comment by fguerout** [comment]
Fixed quickly, thx !

**Comment by kraluk** [comment]
Thanks a lot for a such quick fix!
