### ISSUE TITLE
Update with option --devel and makedepends

### ISSUE THREAD

**Issue by pacorayban** [archlinuxfr/yaourt#155]
When performing yaourt -Syua --devel, some packages are not updated and return error "==> ERROR: Could not resolve all dependencies."

For example freshplayerplugin-git needs ragel as a makedepends, thus it is needed only to compile and ragel can be removed after installation. The expected behaviour would be to install this dependency with option --asdeps as it is done when you compile a package with option "-S".

**Comment by jonnyrobbie** [comment]
I can confirm this. `gimp-git` fails to fetch `gnome-python>=2.16.2` or `pcsx2-git` fails to fetch `png++`.

**Comment by oryband** [comment]
:+1: this also happens with `xcb-util-cursor-git`:
```zsh
==> xcb-util-cursor-git dependencies:
 - libxcb (already installed)
 - xcb-util-renderutil (already installed)
 - xcb-util-image (already installed)
 - git (already installed) [makedepend]
 - xorg-util-macros (package found) [makedepend]
 - gperf (package found) [makedepend]


==> Continue building xcb-util-cursor-git ? [Y/n]
==> ---------------------------------------------
==>
==> Building and installing package
==> Making package: xcb-util-cursor-git 1:0.1.2.r0.g8eb844d-2 (Sun Nov  1 10:21:37 IST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> xorg-util-macros
  -> gperf
==> ERROR: Could not resolve all dependencies.
==> xcb-util-cursor-git is already up to date.
```

**Comment by oryband** [comment]
@Skunnyk @larchunix Finally, thanks! Can I just update yaourt to get this? or do I need to wait for a release?

**Comment by Skunnyk** [comment]
@oryband : you can test it by installing yaourt-git package from AUR. Or you can wait for a release ;)

**Comment by oryband** [comment]
@Skunnyk @larchunix question: installed `yaourt-git`, and when trying to upgrade `i3-gaps-next` i get the following warning. Why is it skipping dependency checks? The problem was that the update failed due to optional dependencies (for example). This warning should not be printed:
```
==> i3-gaps-next-git dependencies:
 - xcb-util-keysyms (already installed)
 - xcb-util-wm (already installed)
 - libev (already installed)
 - yajl (already installed)
 - startup-notification (already installed)
 - pango (already installed)
 - perl (already installed)
 - xcb-util-cursor (already installed)
 - libxkbcommon-x11 (already installed)
 - git (already installed) [makedepend]
 - pkgconfig (already installed) [makedepend]
 - asciidoc (package found) [makedepend]
 - docbook-xsl (package found) [makedepend]


==> Continue building i3-gaps-next-git ? [Y/n]
==> ------------------------------------------
==>
==> Building and installing package
==> Making package: i3-gaps-next-git 4.11.370.g31a2aab-2 (Sun Nov 22 14:50:02 IST 2015)
==> WARNING: Skipping dependency checks.  # THIS WARNING
==> Retrieving sources...
  -> Cloning i3 git repo...
```

**Comment by oryband** [comment]
@Skunnyk @larchunix also, another weird thing just popped up when `yaourt -Syua`ing:
```
:: Synchronizing package databases...
 core                                                                  122.0 KiB  3.31M/s 00:00 [########################################################] 100%
 extra                                                                1808.9 KiB  1577K/s 00:01 [########################################################] 100%
 community                                                               3.1 MiB  2.52M/s 00:01 [########################################################] 100%
 infinality-bundle is up to date
 oh-my-zsh-git : Orphan
 Foreign packages: | 20 / 20
```
Why is `oh-my-zsh-git` orphaned?

**Comment by larchunix** [comment]
@oryband 

> ... the dependencies should be installed and not skipped.

As explained in https://github.com/archlinuxfr/yaourt/pull/171#issuecomment-154549797, upgrading a devel package has two steps: the first one is version check and the second one is build. Dependency checks are skipped during version check but not at build time.

> Why is oh-my-zsh-git orphaned?

Because `oh-my-zsh-git` has no more maintainer in `AUR`.

**Comment by oryband** [comment]
@larchunix thanks.
> As explained in #171 (comment), upgrading a devel package has two steps: the first one is version check and the second one is build. Dependency checks are skipped during version check but not at build time.
then this warning is misleading, and isn't a warning at all when a devel package is the issue. is there a way to hide it for devel packages?

**Comment by larchunix** [comment]
This warning is raised by `makepkg` (https://projects.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in?h=v4.2.1#n3604) and I don't get a reliable way to hide it in `yaourt`.

According to [this comment](https://projects.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in?h=v4.2.1#n3605), `makepkg`'s developers planned to hide this warning in the case that concerns us (i.e: when `makepkg` is used with `-o/--nobuild`) but this has not happened yet.

**Comment by oryband** [comment]
@larchunix any chance to [report this upstream?](https://bugs.archlinux.org/)

**Comment by larchunix** [comment]
Reported as [FS#47149](https://bugs.archlinux.org/task/47149).
