### ISSUE TITLE
Bug in abs.sh that forces every dependency to build from source (ABS)

### ISSUE THREAD

**Issue by memeplex** [archlinuxfr/yaourt#156]
I'm using the devel version of bash but I guess that, no matter the version, `continue` is invalid or, at least, frowned upon here:

https://github.com/archlinuxfr/yaourt/blob/master/src/lib/abs.sh.in#L95

**Comment by memeplex** [comment]
Indeed, the behavior has changed in bash. I will ask Chet Ramey, maybe this is a bug in bash, maybe it's a backwards incompatible behavior.

**Comment by memeplex** [comment]
It's not a bug in bash, it's intentional, so let's this be a heads up.

https://mail.google.com/mail/u/0/#inbox/15051f75ba1629e5

**Comment by Skunnyk** [comment]
Hi,

Thank you for the report.
For the record, the thread on bash mailist : http://lists.gnu.org/archive/html/bug-bash/2015-10/msg00039.html

Maybe it will break a lot of other tools…

**Comment by larchunix** [comment]
@memeplex Please, could you confirm that #211 fixes your issue ?
