### ISSUE TITLE
Yaourt 1.7 -G returns 1 even if the download succeeds

### ISSUE THREAD

**Issue by RazZziel** [archlinuxfr/yaourt#157]
*Expected behavior*: yaourt -G returns 0 when download suceeds
*Actual behavior*: yaourt -G returns 1 even if download suceeds
*Example*:

    ~$ yaourt --version
    yaourt 1.7

    ~$ yaourt -G adom; echo $?
    ==> Download adom sources
    x .SRCINFO
    x LICENSE
    x PKGBUILD
    1
    ~$ ls adom/
    LICENSE  PKGBUILD

    ~$ yaourt -G google-chrome; echo $?
    ==> Download google-chrome sources
    x .SRCINFO
    x PKGBUILD
    x eula_text.html
    x google-chrome-stable
    x google-chrome.install
    1
    ~$ ls google-chrome/
    eula_text.html  google-chrome.install  google-chrome-stable  PKGBUILD

This will be harmless for most users, but it's important for me (and may be for others) because it breaks some scripts.

**Comment by The-Compiler** [comment]
This was fixed in #149.

**Comment by RazZziel** [comment]
Oops, sorry for the dup. Looking forward to the release.

**Comment by Skunnyk** [comment]
Reopen it,  #149  introduce this bug.
Hm, I guess I need to remove https://github.com/cthbleachbit/yaourt/commit/45e23fb46164f19dcdecfd326340659415c202e5#diff-db5e913af13162052895f852c2457da4R411 check as it will return 1 when [[ 0 -ne 0 ]] :]
