### ISSUE TITLE
checkbashisms build fails sha256 check

### ISSUE THREAD

**Issue by stooj** [archlinuxfr/yaourt#160]
I cannot upgrade checkbashisms using yaourt; it fails with a sha256 error.

    ==> Making package: checkbashisms 20150727-1 (Wed Oct 21 12:49:14 AEDT 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Retrieving sources...
      -> Found checkbashisms.1
      -> Found checkbashisms.pl
    ==> Validating source files with sha256sums...
        checkbashisms.1 ... Passed
        checkbashisms.pl ... FAILED
    ==> ERROR: One or more files did not pass the validity check!
    ==> ERROR: Makepkg was unable to build checkbashisms.

However, downloading and building using makepkg works fine:

    $ makepkg
    ==> Making package: checkbashisms 20150727-1 (Wed Oct 21 12:50:17 AEDT 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Retrieving sources...
      -> Downloading checkbashisms.1...
      -> Downloading checkbashisms.pl...
    ==> Validating source files with sha256sums...
        checkbashisms.1 ... Passed
        checkbashisms.pl ... Passed
    ==> Extracting sources...

The PKGBUILD does some unusual stuff with _verscan(), but I'm afraid I do not know enough about the internals of yaourt to guess what the issue might be.

Merci beaucoup!

**Comment by larchunix** [comment]
Strange, I just built checkbashisms-20150727-1 with yaourt and it worked fine for me.

**Comment by stooj** [comment]
Is there any particular information I can provide to help you reproduce this? I can still reproduce it with an up-to-date Arch box, but my Antegros laptop builds the package fine.

**Comment by larchunix** [comment]
According to your copy/paste, makepkg does not download the sources when it is called by yaourt. Therefore, I think you have some leftover source files.
You should probably clean `$TMPDIR/yaourt-tmp-<user>/aur-checkbashisms` and retry. If `TMPDIR` is not set, yaourt uses `/tmp` by default.

**Comment by Skunnyk** [comment]
Is it still an issue ?

**Comment by stooj** [comment]
@larchunix : The files in my copy paste had been downloaded, yep. It was
my second attempt at installing and I'd manually verified that the
checksums were correct. I tried with a clean `$TMPDIR` as well.

I just tried installing again and it worked though! Thanks for the help; I'm not sure what has changed or whether I've grown some brains since then, but it's installing fine.
