### ISSUE TITLE
yaourt -Si: Cannot query remote information

### ISSUE THREAD

**Issue by TecSet** [archlinuxfr/yaourt#161]
Hey there, I got a bug for you:
I found out that querying AUR packages (yaourt -Si) does not always work, even though they are installable by yaourt -S.

For Example:
```text
yaourt -Si backintime-cli
==> ERROR: backintime-cli not found in AUR.
```
```text
yaourt -S backintime-cli
==> Downloading backintime-cli PKGBUILD from AUR...
[...]
```
Thank you for developing Yaourt.

**Comment by f2404** [comment]
Correct me if I'm wrong but I think -Si is not supposed to give info on non-installed AUR packages. You can only query the installed AUR packages by using -Qi.

**Comment by TecSet** [comment]
Sry to correct you but, yaourt -Si does query non-installed AUR packages. For example, try:

```text
yaourt -Si backintime
Repository     : aur
Name           : backintime
[...]
```
Which is not installed on my system which can be seen by:
```text
yaourt -Qi backintime
error: package 'backintime' was not found
```

**Comment by The-Compiler** [comment]
@f2404 I'm pretty sure you are - `-Si` has always worked for me for non-installed AUR packages.

**Comment by TecSet** [comment]
Additional Information which may be interesting are, that there is no .git url with that name:
https://aur.archlinux.org/backintime-cli.git - does not exist
Instead backintime-cli refers to 
https://aur.archlinux.org/backintime.git - does exist
Which can be found here:
https://aur.archlinux.org/packages/backintime-cli/

**Comment by f2404** [comment]
So I was wrong - thanks guys.

**Comment by puckel** [comment]
Hi,

It's not related to .git url, but the PKGBUILD file was not found for backintime-cli (bash -x yaourt -Si backintime-cli) : 

```
~ curl -IL "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=backintime"
HTTP/1.1 200 OK

~ curl -IL "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=backintime-cli"
HTTP/1.1 404 Not found
```
