### ISSUE TITLE
wildcards in pacman.conf Include statement do not work

### ISSUE THREAD

**Issue by hmalzahn** [archlinuxfr/yaourt#164]
yaourt does not support wildcards in an Include statement in pacman.conf. I want to use the same pacman.conf on different machines with different ExcludePkg lines, so I've added the line "Include= /etc/pacman.d/include-*.conf" to the pacman.conf, according to "man pacman.conf". Works fine with pacman, but yaourt gives me the error message "Unable to open file: /etc/pacman.d/include-*.conf"

**Comment by f2404** [comment]
Hi @hmalzahn 
This is a package-query issue actually - please see above.

**Comment by f2404** [comment]
Please check if the patch above fixes the issue for you. Thanks.

**Comment by hmalzahn** [comment]
Yep, this seems to work fine now. No error message, and the "*"-includes are taken into account by yaourt (I've added an "Ignore=mesa*" to one of these files to check).
That was quick!

**Comment by f2404** [comment]
Still have to wait until the patch gets merged and released by @Skunnyk :)

**Comment by hmalzahn** [comment]
Well I ran the test directly with your (unreleased) commit, so that's no problem :) Fortunately, makepkg allows for "#commit=" in the url, so testing patches is very straightforward.

**Comment by Skunnyk** [comment]
Fixed by https://github.com/archlinuxfr/package-query/pull/40 , thank you :)
