### ISSUE TITLE
Saving AUR packages in the cache

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/yaourt#165]
What is the reason why yaourt is not keeping AUR packages in the pacman cache after installing them?
I could find it useful in many cases...

**Comment by larchunix** [comment]
From `yaourtrc(5)` man page:

     BUILD OPTIONS
         EXPORT=2 exports all built packages to pacman cache directory

Is this what you need ?

**Comment by f2404** [comment]
@larchunix 
Thanks! My bad.
