### ISSUE TITLE
Feature request: Make yaourt able to handle AUR dependencies of local PKGBUILDs

### ISSUE THREAD

**Issue by nullptrT** [archlinuxfr/yaourt#174]
The current discussion on aur-general reminds me of an "issue" I have when maintaining my packages: It's much more work to resolve dependencies for local PKGBUILDs.

Since yaourt is a full-featured AUR-dependency-resolver already, it would be nice, if lazy ones could call yaourt in a local directory containing a PKGBUILD (like `yaourt -S --pkgbuild .` or something like that).

I'd help with the implementation, after we've stated
 - if we want that
 - how we want that
 - how the devs woult want that to be implemented.

Comments, please...

**Comment by f2404** [comment]
So what would you like to see as an output of the command?

**Comment by gS644** [comment]
everything that yaourt would do in its tmp directory after downloading a PKGBUILD from AUR, especially:
 - resolving that dependencies in there (won't work, if they are not in AUR yet, but nevermind)
 - invoking `makepkg`

**Comment by f2404** [comment]
So, basically, you'd like to have a way to provide a local PKGBUILD file to yaourt as if it was downloaded from AUR?

**Comment by gS644** [comment]
The only difference would be, that
 - the "normal" `tmp` directory would be the current directory
 - `yaourt` would not download anything

**Comment by gS644** [comment]
@f2404 indeed.

**Comment by gS644** [comment]
As stated in the first post, this feature is not really nessecary and for lazy people, but it is useful ;)

**Comment by f2404** [comment]
I think this could be useful.

**Comment by f2404** [comment]
The PR's been merged - and the issue can be closed, I guess.
