### ISSUE TITLE
assume-installed is not working?

### ISSUE THREAD

**Issue by madhead** [archlinuxfr/yaourt#175]
I have Oracle's JDK installed manually and added to the `PATH`, so `java` is available in the system. Now I want to install [fritzing](https://aur.archlinux.org/packages/fritzing), which requires Java to run:

```shell
pacman --version                                                                                                                                                   

 .--.                  Pacman v4.2.1 - libalpm v9.0.1
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2014 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.

yaourt --version                                                                                                                                                
yaourt 1.7

yaourt -S fritzing                                                                                                                                              

...

==> Continue building fritzing ? [Y/n]
==> ----------------------------------
==> 
==> Building and installing package
==> Install or build missing dependencies for fritzing:
:: There are 2 providers available for java-environment:
:: Repository extra
   1) jdk7-openjdk  2) jdk8-openjdk

Enter a number (default=1):
```

 I do not want to install neither `jdk7-openjdk` nor `jdk8-openjdk` which both provide `java-environment`. So I'm trying to use `--assume-installed` option:

```shell
java -version                                                                                                                                                   
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

yaourt -S fritzing --assume-installed jdk8-openjdk
error: no targets specified (use -h for help)

yaourt --assume-installed jdk8-openjdk -S fritzing
error: no targets specified (use -h for help)

yaourt -S --assume-installed java-environment fritzing
error: no targets specified (use -h for help)

yaourt -S --assume-installed java-environment -- fritzing                                                                                                       
error: no targets specified (use -h for help)
```

All that commands failed. How can I assume that Java is already present on my machine?

**Comment by f2404** [comment]
Can you try it with pacman - will --assume-installed work?
It might be that the option is not passed by yaourt.

**Comment by madhead** [comment]
@f2404, I was able to installa package manually (first install `boost` and `qt5-serialport`) and then building it with `makepkg -srdi`. `makepkg` is checking dependencies on install, so I cancelled it and finished installation with `sudo pacman -U --assume-installed java-environment fritzing-0.9.2b-1-x86_64.pkg.tar.xz`.

The app looks to be ok: it's working and menu shortcuts are created.

**Comment by f2404** [comment]
It looks like yaourt is not supporting ```--assume-installed``` for both AUR and non-AUR packages; but the errors are different so I guess there are 2 issues here.

```
$ yaourt -S --assume-installed sdl_mixer freeciv
resolving dependencies...
looking for conflicting packages...

Packages (4) libmikmod-3.3.7-1  sdl_mixer-1.2.12-4  smpeg-0.4.5-1  freeciv-2.5.1-1
```
```
$ yaourt -S --assume-installed boost fritzing
error: no targets specified (use -h for help)
```

**Comment by mrunion** [comment]
You would be well-served to install the Oracle JDK from the AUR instead of manually. Manually installing packages can (not WILL, but COULD) cause you more trouble down the road. Arch specifically handles Java version and paths in a way that causes little trouble with installed the Oracle JDK or Open JDK versions.

**Comment by madhead** [comment]
@mrunion ok then. Is there any way to install packages into _specific_ locations? What I see in `man`:

```
-r, --root <path>
           Specify an alternative installation root (default is /). This should not be used as a way to install software into /usr/local instead of /usr. This
           option is used if you want to install a package on a temporarily mounted partition that is "owned" by another system.  NOTE: If database path or log
           file are not specified on either the command line or in pacman.conf(5), their default location will be inside this root path.
```

is it ok to use `-r` for current, not another system?

**Comment by larchunix** [comment]
I have opened a PR which should fix your issue. Could you test #225 please ?

**Comment by f2404** [comment]
I think it's still not working for AUR packages...

**Comment by larchunix** [comment]
As `makepkg` checks for dependencies at build time and has no `--assume-installed` flag, I'm afraid there's nothing we can do on `yaourt` side for AUR packages.

**Comment by f2404** [comment]
Oh I see.
So the possible way would be to modify PKGBUILD and remove unwanted dependencies during installation.

**Comment by larchunix** [comment]
Exactly.
