### ISSUE TITLE
prompt response not echoed with NOENTER=0

### ISSUE THREAD

**Issue by oconnor663** [archlinuxfr/yaourt#177]
When I set `NOENTER=0`, I see my response echoed on the first install prompt (`n`), but not the second (should see a `y`):

```
bash> yaourt -S freetype2-ubuntu
...
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
n

==> freetype2-ubuntu dependencies:
 - zlib (already installed)
 - bzip2 (already installed)
 - sh (already installed)


==> Continue building freetype2-ubuntu ? [Y/n]
==> ------------------------------------------
==> 
==> Building and installing package
...
```

**Comment by puckel** [comment]
Set NOCONFIRM=1 too

**Comment by oconnor663** [comment]
I'm setting NOENTER because I want to see the prompts the way I'm used to. NOCONFIRM would skip all the prompts for me, right?

**Comment by larchunix** [comment]
@oconnor663 : For `Y/N` only prompts `stdout` and `stderr` are redirected to `/dev/null` (see https://github.com/archlinuxfr/yaourt/blob/1.7/src/lib/io.sh#L86).

I guess it was coded like this intentionally, does that really bother you ?

**Comment by oconnor663** [comment]
I think that makes sense for the `NOENTER=1` mode, but it feels weird for `NOENTER=0`. Any chance we could make the redirect conditional on that mode?

**Comment by larchunix** [comment]
Could you test #228 please ?

**Comment by oconnor663** [comment]
Looks good! My method:

1) run `yaourt -S dpkg` (or whatever AUR package)
2) When asked to edit the PKGBUILD, type `n` and enter. (Typing here is visible in both versions.)
3) When asked to continue, type `n` and enter. (Typing here is only visible in #228.)

**Comment by oconnor663** [comment]
Contents of my `~/.yaourtrc`:

```
NOENTER=0
```
