### ISSUE TITLE
New users question

### ISSUE THREAD

**Issue by BEMfreshman** [archlinuxfr/yaourt#187]
Hi,
I am a new user to archlinux and have installed archlinux on my laptop last day.
At beginning, yaourt works well and can download packages from repository.
But after rebooting, something may change.
I can still use pacman download packages from official repository, but when I use yaourt,
the download speed is zero and can not show me the total size of packages in terminal.

Anyone can help me with this problems?

PS： I have installed Lantern which can make me  access to some websites blocked.

**Comment by f2404** [comment]
Hi @BEMfreshman 
Does the issue still persist?

**Comment by Skunnyk** [comment]
Test with "bash -x yaourt", to see where it is blocked. 
Maybe a problem on your side.
