### ISSUE TITLE
Yaourt can't build ldmtool

### ISSUE THREAD

**Issue by pakettiale** [archlinuxfr/yaourt#192]
Building ldmtool from AUR fails with the following message:
```bash
./autogen.sh: line 46: ../configure: No such file or directory
/usr/bin/makepkg: line 1564: logpipe: unbound variable
==> ERROR: Makepkg was unable to build ldmtool.
```

This does not happen when building with makepkg nor when using aura (another aur helper), so I guess this is a bug with yaourt??

**Comment by larchunix** [comment]
You can reproduce it manually with `makepkg` by setting the `BUILDDIR` variable e.g:

    BUILDDIR=/tmp/builddir makepkg

The issue is due to the special handling of `BUILDDIR` in `autogen.sh`.

**Comment by larchunix** [comment]
A workaround to avoid the conflict with `BUILDDIR` between `makepkg` and `autogen.sh`, is to edit the `PKGBUILD`. 

The line: `./autogen.sh --prefix='/usr'` 
becomes:  `BUILDDIR='' ./autogen.sh --prefix='/usr'`

IMHO, there is nothing to do `yaourt`'s side.
