### ISSUE TITLE
[request] integreate OBS API

### ISSUE THREAD

**Issue by DeadNumbers** [archlinuxfr/yaourt#195]
OBS - opensuse build system 
https://build.opensuse.org
it would really speed up the build of such packages as the firefox, chromium, kde, etc

**Comment by f2404** [comment]
@DeadNumbers Have you tried using it for building Arch packages?

**Comment by DeadNumbers** [comment]
@f2404 I tried today first time, but I was not able to build firefox. But, OBS support Arch packages http://openbuildservice.org/2013/04/30/version-2.4/
