### ISSUE TITLE
Segmentation fault on package search

### ISSUE THREAD

**Issue by kozross** [archlinuxfr/yaourt#201]
When I try to run ``yaourt open sans``, I get the following error when it tries to search AUR packages:

```
/usr/lib/yaourt/util.sh: line 166:  8443 Segmentation fault      (core dumped) package-query "${PKGQUERY_C_ARG[@]}" "$@"
```

I'm using yaourt 1.7.

**Comment by f2404** [comment]
It looks very similar to #152 and is supposed to be fixed in 1.7.
My installation (```yaourt-git``` and ```package-query-git```) works fine. Can you try the git versions?

**Comment by kozross** [comment]
Installed git versions - works fine.

**Comment by f2404** [comment]
So the issue may be closed, I think.

**Comment by Skunnyk** [comment]
Yup, fixed
