### ISSUE TITLE
Too many packages are displayed when searching

### ISSUE THREAD

**Issue by AndrewBelt** [archlinuxfr/yaourt#208]
I use a non-scrolling terminal, and running a search command like `yaourt iceweasel` returns 95 results so that the most relevant terms are gone.

A workaround is to use a pager such as less, but I cannot enter the package number in the same command. I must run the command again without the pager and hope that the package number didn't change.

I suggest either adding a command line option to select only the first n results, or implementing a pager-like behavior which displays the first n packages and asks for a number or 'Enter' to display the next page of results.

**Comment by f2404** [comment]
Could the ```head``` utility help? For example, the following would show the first 20 lines:
```yaourt iceweasel | head -n20```

**Comment by puckel** [comment]
Like apt-cache, an option `--names-only, -n` would be great to search in package name only

**Comment by stevleibelt** [comment]
@f2404 

I am doing the same or 

```
yaourt  -Ss <package name> | grep <package name>
```

**Comment by f2404** [comment]
@puckel 
We already have this options since https://github.com/archlinuxfr/yaourt/commit/3f34fc4e087ba56df8ff3e2e3b25c09c06c7eed9

**Comment by f2404** [comment]
@stevleibelt 
If you know the exact package name, you can use ```--nameonly``` as well.

**Comment by stevleibelt** [comment]
@f2404 

thanks, I wasn't aware of this flag. Thank you :).

**Comment by f2404** [comment]
You are welcome :)

**Comment by f2404** [comment]
@AndrewBelt Do the options mentioned above resolve your issue?

**Comment by f2404** [comment]
@larchunix Do you think we should add some improvement here, or `--nameonly` together with `head` and `tail` are actually enough?

**Comment by larchunix** [comment]
@f2404 I think `head` and `tail` are enough adding a `--limit` style option is not worth it.

**Comment by larchunix** [comment]
@AndrewBelt: The pager like behaviour already exists in `yaourt`. You can add `--pager` to your command line or set `USEPAGER=1` in `yaourtrc`.

**Comment by AndrewBelt** [comment]
@larchunix I didn't notice this. After setting $PAGER and editing the yaourtrc, yaourt behaves as I'd like, since search results are now usable.
