### ISSUE TITLE
Order when sorting results by votes?

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/yaourt#210]
The question is the same as https://github.com/archlinuxfr/package-query/issues/74 but for a larger audience.

When sorting search results by AUR votes (```yaourt -Ss package --sort w```), should we expect the most voted packages be shown first or last?
I'd think that higher position in the resulting list would indicate more votes - but the current implementation puts the packages in the ascending order which means: more votes - the lower position.

**Comment by puckel** [comment]
:+1: for most voted packages to be shown in the top of the output

**Comment by f2404** [comment]
@puckel Thanks for your opinion!

**Comment by f2404** [comment]
The most voted and most popular packages will be shown first.

**Comment by jayypluss** [comment]
How does `--sort` works? I can't find anything about it at `yaourt -Ss --help`.
It doesn't sort by default: 
![yaourt-001](https://user-images.githubusercontent.com/17395606/40634729-ecc9ee28-62cc-11e8-96b2-daf722cc0243.gif)

**Comment by f2404** [comment]
Sorting is done by package-query.
