### ISSUE TITLE
Yaourt unable to locate any AUR package dependencies that are specified with a version

### ISSUE THREAD

**Issue by lots0logs** [archlinuxfr/yaourt#212]
Possibly related to #1. When a package dependency is specified with a version (`some-package>=2.0`) yaourt can't find it. The most recent example of the issue that I found is with `python-neutronclient` which depends on `python-os-client-config>=1.13.1` which is available in the AUR yet yaourt can't find it.

**Comment by larchunix** [comment]
Your issue is most likely similar to #85.

Current `PKGBUILD` parsing in `yaourt` does not handle split package specific variables (i.e: defined within `package_<package_name>()` functions in `PKGBUILD`).

**Comment by lots0logs** [comment]
Yep, you are correct. This is a duplicate of #85. Sorry!
