### ISSUE TITLE
yaourt -G lib32-package download nothing from ABS| curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by FadeMind** [archlinuxfr/yaourt#219]
@Skunnyk  

If you want download source lib32-libname, then yaourt download nothing. Only empty directory with lib32-libname is created.

Additonal: curl have error 404:

[tomasz@arch ~]$ export LANG=C
[tomasz@arch ~]$ yaourt -G lib32-gtk3
==> Download lib32-gtk3 sources
==> multilib/lib32-gtk3: Download abs archive

curl: (22) The requested URL returned error: 404 Not Found
[tomasz@arch ~]$ 

but package lib32 packages sources from AUR are downloaded:

[tomasz@arch ~]$ yaourt -G lib32-ffmpeg
==> Download lib32-ffmpeg sources
Cloning into '.'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 4 (delta 0)
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
[tomasz@arch ~]$ 

URLs:

https://www.archlinux.org/packages/multilib/x86_64/lib32-gtk3/
https://www.archlinux.org/packages/multilib/x86_64/lib32-glibc/

and so on.

**Comment by larchunix** [comment]
ABS tarball (http://mirror.rackspace.com/archlinux/multilib/os/x86_64/multilib.abs.tar.gz) is missing for `multilib` repo whereas it exists for other repos (http://mirror.rackspace.com/archlinux/core/os/x86_64/core.abs.tar.gz).

```
sudo abs --tarball
==> Downloading tarballs...
    ==> core...
    ==> extra...
    ==> community...
    ==> multilib...
==> ERROR: Download failed
```

It should works if you install `rsync` or set `USE_GIT=1` in `yaourtrc`.

**Comment by FadeMind** [comment]
@larchunix 
I enabled ABS `USE_GIT=1` in `yaourtrc` and WORKING. Thanks.
