### ISSUE TITLE
Error after pacman (5.0.0-1) upgrade

### ISSUE THREAD

**Issue by dR3b** [archlinuxfr/yaourt#221]
Hi,
I got this error after **pacman** (5.0.0-1) upgrade:
```
user1@pc1 ~ % sudo pacman -S archlinuxfr/yaourt
resolving dependencies...
warning: cannot resolve "pacman<4.3", a dependency of "package-query"
warning: cannot resolve "package-query>=1.4", a dependency of "yaourt"
:: The following package cannot be upgraded due to unresolvable dependencies:
      yaourt

:: Do you want to skip the above package for this upgrade? [y/N] N
error: failed to prepare transaction (could not satisfy dependencies)
:: package-query: requires pacman<4.3
:: yaourt: requires package-query>=1.4

```
```

user1@pc1 ~ % sudo pacman -Ss pacman
core/pacman 5.0.0-1 (base base-devel) [installed]
    A library-based package manager with dependency support

**Comment by f2404** [comment]
@Skunnyk It looks like a good reason to release `package-query`/`yaourt` with `pacman 5.0` support :)

**Comment by f2404** [comment]
@dR3b Switching to git versions (`package-query-git`, `yaourt-git`) could be a temporary solution.

**Comment by Skunnyk** [comment]
The AUR package for package-query is now update

**Comment by benjarobin** [comment]
testdb no longer exist :
pacman can check the validity of the local and sync databases  (-Dk and -Dkk respectively).  This replaces the 'testdb' software (FS#42444)

**Comment by f2404** [comment]
@benjarobin Thanks - created issue #222

**Comment by larchunix** [comment]
`testdb` error should be fixed by #223.

**Comment by dR3b** [comment]
Works! Thanks

**Comment by f2404** [comment]
@dR3b Great! The issue can be closed, I guess?

**Comment by dR3b** [comment]
Yes please.

**Comment by larchunix** [comment]
Reopen to avoid more duplicates.

**Comment by larchunix** [comment]
The storm should be over.
