### ISSUE TITLE
Yaourt does not appear to play nice with pacman 5

### ISSUE THREAD

**Issue by kozross** [archlinuxfr/yaourt#224]
I get the following error when trying to 'yaourt -Syua':

package-query: error while loading shared libraries: libalpm.so.9: cannot open shared object file: No such file or directory

**Comment by f2404** [comment]
@kozross You have to rebuild `package-query` after updating `pacman` to version 5.0.
Please also see https://github.com/archlinuxfr/package-query/issues/90
and comments to the AUR package: https://aur.archlinux.org/packages/package-query/

**Comment by larchunix** [comment]
Duplicates #221.
