### ISSUE TITLE
The aur change their API 

### ISSUE THREAD

**Issue by ruizhipeng** [archlinuxfr/yaourt#237]
I'm a fresher from China and maybe my English is hard to understand ,but I hope that you and your team can fix the problem if you have enough time ,best wishes.

**Comment by f2404** [comment]
Does installing package-query-1.8 solve the issue, @ruizhipeng ? It supports AUR RPC 5.

**Comment by ruizhipeng** [comment]
thank you so much , have a good day.problem fixed ^_^

**Comment by f2404** [comment]
You're welcome :)
