### ISSUE TITLE
yaourt -C does show wrong options with different LANG e.g. de_DE.utf8

### ISSUE THREAD

**Issue by banholzer** [archlinuxfr/yaourt#242]
when LANG is set to something different like de_DE.utf8 instead of en_US.utf8 yaourt shows localized German Options, but won't accept them.

==> .pacnew: /etc/postfix/aliases
==> Aktion: [B]earbeiten, [E]rsetzen, [I]gnorieren, [F]ortfahren (Standard), [A]bbrechen?

this wouldn't accept B for edit or E for replace. It accepts the "original" English options.
==> .pacnew: /etc/postfix/aliases
==> Action: [E]dit, [R]eplace, [S]uppress, [C]ontinue (default), [A]bort ?

workarount with setting different LANG works, but it took me some time to realize what's the real problem with managing pacnew files and yaourt.

**Comment by larchunix** [comment]
Several translations have been lost during a previous commit. I have updated `yaourt.pot` with the missing strings from `pacdiffviewer` (7f11a3c). It will take time before translations are updated.

@Skunnyk Could you push the new version of `yaourt.pot` to transifex ?

**Comment by larchunix** [comment]
Version 1.8.1 should fix this issue.
