### ISSUE TITLE
yaourt calls /usr/lib/yaourt/util.sh which calls package-query and then core dumps

### ISSUE THREAD

**Issue by dtschmitz** [archlinuxfr/yaourt#248]
http://i.imgur.com/YWbYvTx.png

I think the params for package-query have changed but aren't correctly passed in util.sh

Please review and advise.
Kindest Regards

**Comment by larchunix** [comment]
Did you compile package-query from AUR or did you install it from archlinuxfr repository ?

**Comment by dtschmitz** [comment]
That is precisely my mistake.  I am up and running now.
All set -- have a great day.
