### ISSUE TITLE
Bad translation - key mapping

### ISSUE THREAD

**Issue by VNovotna** [archlinuxfr/yaourt#249]
![snimek obrazovky porizeny 2016-03-08 20-10-02](https://cloud.githubusercontent.com/assets/3995985/13612829/cf44e0b6-e569-11e5-9c43-fafd517b73e5.png)
When I want to selectively choose packages to update, dialog suggest R key as "[R]učně", but the actual mapping s M as "[M]anualy".

**Comment by larchunix** [comment]
Which locale do you use ?

**Comment by VNovotna** [comment]
Sorry I fogot to specify it. System Locale: LANG=cs_CZ.UTF-8

**Comment by larchunix** [comment]
This particular translation should be fixed in yaourt-git by 437f9a1.

Some Czech translations still looks wrong to me e.g:

    #: ../../lib/pkgbuild.sh.in:324
    msgid "[v]iew package contents   [c]heck package with namcap"
    msgstr "[z]obrazit obsah balíku   [z]kontrolovat balík s nástrojem namcap"

`[z]` shouldn't be used twice here.

I don't speak Czech so I can't fix it. You can fix them on https://www.transifex.com/archlinuxfr/yaourt/ if you are willing to do so.

**Comment by VNovotna** [comment]
Well both of those words starts with z, but this clearly wrong.
By my first impression from transifex, Czech translation isn't really perfect. I'll look at it tomorrow. I think I can help.
