### ISSUE TITLE
Automatically create btrfs snapshots prior to upgrading or installing new packages

### ISSUE THREAD

**Issue by banholzer** [archlinuxfr/yaourt#250]
Hello,

this is a question - not a bug / issue. 

I don't know if this was ever been discussed. On ubuntu there is a package called apt-btrfs-snapshot, which creates btrfs snapshots before running operations that could harm your system (like upgrade, dist-upgrade or install).

I think such a feature would be nice to have in yaourt. To configure in /etc/yaourtrc and with features like:

- creating snapshot when using -Su switch
- creating snapshot when using -S switch
- creating snapshot when using -R switch
- deleting old snapshots (as configured e.g. max-keep-count or max-age)
- possibility to additionally snapshot /boot if this is a separate btrfs file system (e.g. on encrypted systems) - this will keep system states that are bootable if kernel was upgraded since last snapshot
- configurable directory where to do the btrfs work (mount subvol=/ ...)
- configurable source subvolume

If you are interested in such a feature, I'll try to implement this. (Already have a script for this on my system)

**Comment by f2404** [comment]
I'm not using btrfs but I think this could be an interesting feature.

One thing I'd like to point out is that this shouldn't be part of `yaourt`, in my opinion. I believe the snapshot functionality should be implemented in a separate tool (optionally installed) that `yaourt` could make use of.

**Comment by larchunix** [comment]
I think more people could benefit from this feature if it was implemented using [alpm-hooks](https://projects.archlinux.org/pacman.git/tree/doc/alpm-hooks.5.txt) instead of adding snapshot support to yaourt.

Maybe a "simple" wrapper for [snapper](https://www.archlinux.org/packages/community/x86_64/snapper/) could do the job.

**Comment by ArchangeGabriel** [comment]
You might want to take a look at snap-pac:
https://aur.archlinux.org/packages/snap-pac/
https://github.com/wesbarnett/snap-pac

**Comment by banholzer** [comment]
ok it looks like snap-pac is it. So someone else already built a solution for this.

Anyway, thanks for your help.
