### ISSUE TITLE
Upgrading a package from file sometimes causes stdin warning

### ISSUE THREAD

**Issue by drewmnoel** [archlinuxfr/yaourt#256]
On some packages, `yaourt -U <file>` causes a warning:

```
$ yaourt -U test-yaourt-1-1-x86_64.pkg.tar.xz 
error: argument '-' specified without input on stdin
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) test-yaourt-1-1

Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] 
```

[PKGBUILD](https://gist.github.com/drewmnoel/a91c1ccbe699e2ece117) used to generate this package.

This happens, for example, when installing `linux-git-headers` as well.

**Comment by f2404** [comment]
@drewmnoel 
Could you please check if this patch resolves the issue for you? https://github.com/f2404/yaourt/commit/55d43eed9781aab90d63d9c3ba004539f030a873

**Comment by drewmnoel** [comment]
@f2404 it does indeed. Sorry about that.

**Comment by f2404** [comment]
@drewmnoel You don't need to be sorry - this is the real issue you are reporting, and I've just created a fix for it.
I will submit a PR since you've confirmed it works. Thank you.

**Comment by milouse** [comment]
I still have the problem, as shown is the following capture:
![capture](https://user-images.githubusercontent.com/349239/27322169-54cd2d70-559d-11e7-8b0e-5bf8e4f0fba5.png)

I suspect some weird problem, due to the number of dashes in the package name (I only encounter the problem with long/complex package name).

**Comment by milouse** [comment]
Ok I just check my yaourt version and saw that it has been released before the resolving PR. Will a new version be released any time soon?
