### ISSUE TITLE
Search results do not match those on AUR site when multiple targets specified

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/yaourt#266]
E.g., running `yaourt -Ss git client` gives `AUR error : Too many package results.`
This is happening because currently only first target is searched, i.e. 'git'.

The AUR site search, however, responds with 378 packages: https://aur.archlinux.org/packages/?O=0&SeB=nd&K=git+client&outdated=&SB=n&SO=a&PP=50&do_Search=Go
The issue is that I do not understand how this result may be achieved by using AUR RPC.
Searching for '&arg=git client' (as when running `yaourt -Ss "git client"`) gives 2 packages.
Searching for '&arg=git&arg=client' gives 1370 packages - apparently, it outputs the packages containing git or client in their names or descriptions, while AUR site outputs the packages containing both git and client.

Any ideas are welcome.

UP I've submitted a task on the bug tracker: https://bugs.archlinux.org/task/49133?project=2

**Comment by rmarquis** [comment]
It's another bug in yaourt query with short arguments:

```
$ yaourt -Ssq git client | wc -l
AUR error : Too many package results.
2
$ yaourt -Ssq -client git | wc -l
379
```

Two packages are actually in the repo (`bitcoin-cli` and `steam`), so there is 377 results from the AUR. I have no idea what is the missing package.

**Comment by f2404** [comment]
Yeah, that's funny... Thanks for noticing, @rmarquis !

**Comment by f2404** [comment]
OK, I found the missing packages - it's https://aur.archlinux.org/packages/tinc-pre-git/
It's actually does not have 'client' in its name or description. But it has it among its keywords, and looks like a bug that AUR includes Keywords into search fields while told to search by name and description.

**Comment by f2404** [comment]
Fixed by https://github.com/archlinuxfr/package-query/commit/8d89caf02495a13f7a78985091084838f4a1f0f0
(except for the extra package shown by mistake).
