### ISSUE TITLE
Show only 20 results!

### ISSUE THREAD

**Issue by saintplay** [archlinuxfr/yaourt#267]
Hello, if I search packages like

``` bash
yaourt go
```

Yaourt give me a 2112 results, I want to see just the 30, 20 or 10 top results.
Any way to do this?

**Comment by ArchangeGabriel** [comment]
You mean, a feature for pages like gpg key search? That could be nice.

**Comment by f2404** [comment]
You can use pager for that (see yaourt man). E.g.:
`PAGER=less yaourt --pager go`

**Comment by djap96** [comment]
I found a a topic on [reddit](https://www.reddit.com/r/archlinux/comments/4ao2ja/yaourt_often_too_many_package_choices_cant_scroll/). The `--pager` option is amazing and solves my problem.
PD: `--color` doesn't work with `--pager` for me

**Comment by f2404** [comment]
I was able to retain colors by running `PAGER='less -R' yaourt --pager --color go`

**Comment by djap96** [comment]
@f2404 Thanks

**Comment by f2404** [comment]
@djap96 You are welcome. The issue may be closed, I guess?

**Comment by xahon** [comment]
May be this construction `PAGER='less -R' yaourt --pager --color go` should be extracted into its own flag or `--pager` will `--color` and `less -R` it by default?  
  
__P.S.__ also you can't interrupt that command with `ctrl+c` and it behaves differently from original  command without pager (you need to press `q` anyway and then either enter a number or press `ctrl+c`)
