### ISSUE TITLE
[feature request] split package

### ISSUE THREAD

**Issue by mattia-b89** [archlinuxfr/yaourt#270]
make yaourt smarter, in order to handle split packages updates.
e.g. I've installed linux-ck and linux-ck-headers that are both provided by the linux-ck base package;
when I'm going to update it, yaourt prompts to compile and install the first one; when the task is completed and both linux-ck and linux-ck-headers  have been installed, yaourt asks me to compile and install the second package in the list, the linux-ck-headers one... but this has already been installed by the previous task!

maybe the simplest (but not the best and finest) solution is to perform a check of needed packages after every package installation...

**Comment by larchunix** [comment]
Yep, it is a long standing issue : see #85, #212 and #247.
