### ISSUE TITLE
Endless "File Owned By" Spam error messages...

### ISSUE THREAD

**Issue by NovaCygni** [archlinuxfr/yaourt#271]
Im sure someone decided having yaourt spam endless walls of text telling me obvious and pointless shit was a useful feature, but knowing that "file owned by 'bettercap' and 'ssrf-proxy'" or that "file cheetah is owned by cheetah"... alas, these messages are spam, personally checked all 314 of the bullshit error messages, everything runs perfectly fine and the "Ownership" matter is only a issue at all because yaourt is obsessed with throwing this crap in my face all the time.....
either:
a) Supress or add a option to supress "Warning" level error messages
b) Supress or a add a option to supress POST FUNCTION  checks, ie, if I do 'yaourt -S foobar' I have frankly once foobar is installed no desire nor care to know about all other packages on the system.... 
Some of the errors are laughably pathetic "Error"s due to the fact that frankly, I expect VLCs packages to be owned about VLC or Nessus services to be owned by Nessus.... even Postgresql is also, supposed to be make the database for other services that use it, thus the entirety of the warnings are pointless... endless... spam.

**Comment by f2404** [comment]
These messages are coming from pacman, not from yaourt.
It's something wrong with your system as such messages shouldn't appear normally.
Mind your language.

**Comment by NovaCygni** [comment]
pacman produces 0 errors, Octopi produces none, the older versions of yaourt do NOT produce the errors, thus downgrading removes the spam issue... the issue is encountered when using the latest version of yaourt thus, something must have changed.
Im far from the only one with this issue as we've people coming to both the Archlinux and Manjaro freenode channels who've mentioned the issue before on numerous occasions.
The system works perfectly fine, as do all the Archlinux installs Ive done this week, including BlackArch, the issue appears when yaourt is upgraded to the latest version. 
Worth noting is the yaourt messages also state inaccurate information such as "Metasploit is owned by metasploit" when a quick check shows that the ownership is "users" and is exactly what it should be.
No Profanities have been issued ive just been frank about the annoying nature of the walls-of-spam...

**Comment by larchunix** [comment]
See #241
