### ISSUE TITLE
yaourt -Sw <package-name> results in "error: target not found" for all AUR packages

### ISSUE THREAD

**Issue by PawkyPenguin** [archlinuxfr/yaourt#273]
For example, executing the above stated command has the following result:
`$ yaourt -Sw xinput_calibrator`
`error: target not found: xinput_calibrator`

Running `yaourt -S xinput_calibrator` installs the package as expected.

**Comment by f2404** [comment]
What do you expect to achieve by running `yaourt -Sw <aur_package>`?

**Comment by PawkyPenguin** [comment]
My bad, I didn't even check whether -w existed as an argument, because I expected a different error message in that case. Under pacman, it downloads the package but doesn't install it. 

I guess this just became a mini-feature request.

**Comment by f2404** [comment]
The thing is that `-w` is passed directly to pacman which responds with the error you're seeing.
I think yaourt could support this option for AUR packages if there are both understanding what result it should provide, and that this result is valuable. Just a note: you can already get AUR package's PKGBUILD by running `yaourt -G`.
