### ISSUE TITLE
pkgbuild diffs can interrupt a --noconfirm install/upgrade

### ISSUE THREAD

**Issue by Alexendoo** [archlinuxfr/yaourt#277]
When upgrading with pkgbuild diffs enabled, if the diff is large enough a pager is typically used requiring manual intervention, it might as such be best not to display diffs when doing an install/upgrade with --noconfirm

**Comment by larchunix** [comment]
Hi,

Thanks for the report.

3f0818e should fix your issue. The diff is displayed in all cases but the option `--no-pager` is added to `git diff` if `--noconfirm` is used on `yaourt` side.
