### ISSUE TITLE
Bad --noprogressbar handling behaviour

### ISSUE THREAD

**Issue by AstroSnail** [archlinuxfr/yaourt#279]
When I run the following:
`$ yaourt -Syy package-name --noprogressbar`
the progress bars are disabled as expected, but I also get this error:
`error: invalid option '--noprogressbar'`
in the middle of output.
I eventually concluded that yaourt was passing the --noprogressbar option to pacman where it isn't valid, such as with the -D operation.
I looked into the script and, surely enough, found support to my hypothesis in line 392:
`--noprogressbar)    program_arg $A_PC $1;;`
which is allowing --noprogressbar for any operation instead of just -S, -R and -U.
I subsequently edited the line as follows:
`--noprogressbar)    program_arg $((A_PS | A_PU)) $1;;`
which passes the argument only for the operations -S and -U (since the operation bitmask thing in /usr/lib/yaourt/util.sh doesn't include -R)
I tested it, and the errors went away. However, when syncing the databases, the progress bars are still shown. This leads to the unusual behaviour of having progress bars for the database downloads, but none for the package download and installation, even when both arise from the same pacman call. This leads me to think yaourt is calling pacman for updating databases and for installing packages separately, and not using either -S or -U for updating the databases.
I don't think yaourt is handing the --noprogressbar option correctly.

**Comment by larchunix** [comment]
Indeed, this is spaghetti code. Database syncing is done using the function [`pacman_refresh()`](https://github.com/archlinuxfr/yaourt/blob/1.8.1/src/lib/pacman.sh.in#L55-61).

**Comment by larchunix** [comment]
Fixed by #283.
