### ISSUE TITLE
"Default" key handling causes unexpected behavior

### ISSUE THREAD

**Issue by vn971** [archlinuxfr/yaourt#284]
Hi! I have a recurring problem with yaourt key handling.

The problem occurs when I press a key that is not normally handled by yaourt, which is considered by `yaourt` as the default action in the current context.
Most typically I just press a key in non-english language, often a key that meant to be "no" or "view files". `yaourt`, however, assumes I issued the default action ("yes") and does something I did not wish in the first place.

Did I describe the issue clear enough, any questions? Thoughts?

**Comment by larchunix** [comment]
IIRC, this should have been fixed by #230. Could you try using git version of yaourt ?

**Comment by vn971** [comment]
(Not using yaourt anymore, not able to provide usable information anyway.)
