### ISSUE TITLE
redundant info in 'unable to remove pkg due to dependency' message

### ISSUE THREAD

**Issue by derSteFfi** [archlinuxfr/yaourt#288]
When trying to remove a package that is still needed by another package, yaourt throws this:
```
yaourt -R rtkit
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: pulseaudio: removing rtkit breaks dependency 'rtkit'
```
Is rtkit doubled here by intent? I can't see why and think is redundant.

**Comment by f2404** [comment]
It's actually `pacman`'s message (try `pacman -R rtkit`).

I think package name might be put twice for the reason that sometimes package name and dependency name do not match: e.g., a package could 'provide' something having a different name. So I think `pacman` devs were avoiding any misunderstanding here.

**Comment by derSteFfi** [comment]
*sigh* Sorry, I was already getting confused why I couldn't find the strings in po/yaourt :)

nevermind, nothing to see ...
