### ISSUE TITLE
[typo/cosmetic issue] suppress "ex"

### ISSUE THREAD

**Issue by mattia-b89** [archlinuxfr/yaourt#312]
I am not a native English speaker but I've never seen a such thing "ex"
I am talking about:

==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------

If I want to write the short form of example, you should use "e.g." or "i.e."
Anyway, I think we can easily suppress it .... when answer is yes or no, in the square brackets nobody puts example, e.g. or i.e

**Comment by bunder** [comment]
Links to support @mattia-b89 point of view:

- https://english.stackexchange.com/questions/16197/whats-the-difference-between-e-g-and-ex
- https://forum.wordreference.com/threads/ex-for-example.1772384/
