### ISSUE TITLE
package-query complains about "invalid option"

### ISSUE THREAD

**Issue by sn0w** [archlinuxfr/yaourt#313]
When upgrading packages, package-query shows an error message instead of the old/new package versions.

![](https://i.imgur.com/Jnf0Etp.png)

I'm using yaourt 1.8.1 and package-query 1.8

**Comment by f2404** [comment]
What are your yaourt and package-query versions?

**Comment by f2404** [comment]
Also, does `sudo pacman -Syu` work fine?

**Comment by sn0w** [comment]
Yes that works.

**Comment by f2404** [comment]
@sn0w What are the components versions?

**Comment by sn0w** [comment]
yaourt 1.8.1
package-query 1.8
pacman 5.0.1-4

Or you you mean something else?

**Comment by f2404** [comment]
No, that's what I mean.
Can you check if -git versions of yaourt and package-query will solve the problem for you? I have no issues with them.

**Comment by f2404** [comment]
Also, can you share your ~/.yaourtrc, /etc/yaourtrc and /etc/pacman.conf?

**Comment by sn0w** [comment]
- ~/.yaourtrc does not exist
- /etc/yaourtrc is the default (everything commented)
- /etc/pacman.conf below (commented lines stripped)
```ini
[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
```

Also i tested the `-git` versions and the issue persists :disappointed:

**Comment by f2404** [comment]
Ok, thanks.
Now, can you run `bash -x yaourt -Syu` and share the output?

**Comment by sn0w** [comment]
https://gist.github.com/sn0w/20775e87708ef0abe2dde934a2226771

**Comment by f2404** [comment]
This line looks problematic:
`++ package-query --aur-url https://aur.archlinux.org -1Sif '%n %r %v %l %d' '[b' c a 'e]' '[a' b c 'e]' '[e' c b 'a]' '[0.1' -1.6 1.5 9 -8 0.01 '1e+99]' '[-8' -1.6 0.01 0.1 1.5 9 '1e+99]'`
But I don't understand what it's supposed to mean. What packages are going to be updated (you can check it with pacman since yaourt isn't working)?

**Comment by sn0w** [comment]
I'll close this issue because I switched to another tool.
Thanks for your insanely fast support @f2404 :)

**Comment by f2404** [comment]
> I'll close this issue because I switched to another tool.

@sn0w It's sad but it's definitely your right. And you're welcome :)
