### ISSUE TITLE
flite1 fails to build

### ISSUE THREAD

**Issue by bermond** [archlinuxfr/yaourt#317]
yaourt fails to build [flite1](https://aur.archlinux.org/packages/flite1/) (AUR package). I get the following error when trying to build it on x86_64:
```
ar: ../../..//tmp/yaourt-tmp-user/aur-flite1/lib/libflite.shared.a: No such file or directory
make[2]: *** [../../config/common_make_rules:116: /tmp/yaourt-tmp-user/aur-flite1/obj/src/audio/.build_so] Error 1
make[1]: *** [../config/common_make_rules:133: /tmp/yaourt-tmp-user/aur-flite1/obj/src/.make_build_dirs] Error 2
make: *** [config/common_make_rules:133: /tmp/yaourt-tmp-user/aur-flite1/obj//.make_build_dirs] Error 2
```

It's building perfectly with packer and pacaur so it looks like a specific yaourt issue.

**Comment by f2404** [comment]
Indeed, I can reproduce it here.

The comment on AUR is saying:
NOTE: If you have trouble installing this package with yaourt, just download the package with `yaourt -G flite1` and run `cd flite1` and then `makepkg -i`. It should build and install all right. Or you can use the binary packages at http://l2orkaur.bitbucket.org/.

**Comment by bermond** [comment]
@f2404 
Thank you for the reply and support.

Yes, I've seen that message pointing a workaround, but this works only when building it alone. The big problem is when [flite1](https://aur.archlinux.org/packages/flite1/) is being builded as a dependency of another package because the given one will also fail to build. For example, [ffmpeg-full-git](https://aur.archlinux.org/packages/ffmpeg-full-git/) fails to build with ```yaourt -S ffmpeg-full-git```.

I hope this can be fixed by the next yaourt release.

**Comment by f2404** [comment]
Yep, I can confirm but I have no idea about its cause.

**Comment by rmarquis** [comment]
This happens because yaourt doesn't do clean build. See link [13] in the [comparison table](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table).
You could also probably fix [12] more or less easily.

**Comment by bermond** [comment]
@rmarquis 
Thank you for the answer, now I understand what's happening. Unfortunately this is made by design in yaourt and it will intentionally fail to build any package that has makefile's variable names also used by makepkg, like BUILDDIR used in flite1 makefile. I hope this behavior can be changed in future.

A "fix" to make flite1 work with ```yaourt -S``` (and ```yaourt -P```) would be to change the BUILDDIR variable in makefile to another name. A simple sed in prepare() will do the job, for example: ```sed -i 's/BUILDDIR/_FLITE1_BUILDPATH/g' config/common_make_rules```.

**Comment by bermond** [comment]
I have placed a message in the flite1 AUR page and the maintainer commited my suggested "fix". Now it's building fine with yaourt. Also tested with plaing makepkg, packer and pacaur.
Thanks to everyone who participated here.
Closing this issue.

**Comment by rmarquis** [comment]
While this workarounds the issue for flite1, the underlying is *not* fixed and this bug potentially affects a whole other range of packages. The design of yaourt should be changed.
