### ISSUE TITLE
Ask all the questions first, then execute everything else

### ISSUE THREAD

**Issue by maximbaz** [archlinuxfr/yaourt#324]
I'd like to be able to schedule an installation / an upgrade and leave the terminal while yaourt is doing its job. 

However, it is not currently possible with yaourt, as it will keep pausing and waiting for me to respond on some questions (edit PKGBUILD of package and later each dependency, typing "Y" to install, etc).

Instead I'd like yaourt to look upfront what is going to be installed / upgraded, ask me all the questions, and when I'm done answering, start the installation and run it without pausing until the very end.

`yes | yaourt --noconfirm -Syyua --devel` is not an acceptable workaround 🙂

**Comment by samzorn** [comment]
in my opinion and I'm only an absolut beginner on this topic is it not possible to do that without a large effort.. my thought depends on basic programming knowledge... what you describe is more a behavior of declarativ programming used for DBs (hope i tell the truthl) or maybe AI.in this case the code describe what should be achieved but don't tell how... and in the other case for example... what a program like yaourt do is called imperativ programming. shortly said.. begin on top of code and go to bottom with instruments like loops, functions, arrays etc.... here you tell how sth. can achieved...  for this reason  it MAYBE difficult to do what you  want  especially with a scripting language in my thought.    i give no warranty for thd correctness of my rash thoughts. but when it is possible what you want i need to know how and why.... LEARNING NEVER STOP. and that is why i go from windows to linux. i love become more experienced. 
i hope not all is wrong 😂

maybe a idea is.... sth like yaourt...... - -noconfirm  - -quiet  puts you in the right direction.. 


sorry for my bad english 😳

**Comment by samzorn** [comment]
@maximbaz in my opinion and I'm only an absolut beginner on this topic is it not possible to do that without a large effort.. my thought depends on basic programming knowledge... what you describe is more a behavior of declarativ programming used for DBs (hope i tell the truthl) or maybe AI.in this case the code describe what should be achieved but don't tell how... and in the other case for example... what a program like yaourt do is called imperativ programming. shortly said.. begin on top of code and go to bottom with instruments like loops, functions, arrays etc.... here you tell how sth. can achieved... for this reason it MAYBE difficult to do what you want especially with a scripting language in my thought. i give no warranty for thd correctness of my rash thoughts. but when it is possible what you want i need to know how and why.... LEARNING NEVER STOP. and that is why i go from windows to linux. i love become more experienced.
i hope not all is wrong￼

maybe a idea is.... sth like yaourt...... - -noconfirm - -quiet puts you in the right direction.. oh just saw you wrote down the same idea... lool

sorry for my bad english￼

**Comment by samzorn** [comment]
@maximbaz in my opinion and I'm only an absolut beginner on this topic is it not possible to do that without a large effort.. my thought depends on basic programming knowledge... what you describe is more a behavior of declarativ programming used for DBs (hope i tell the truthl) or maybe AI.in this case the code describe what should be achieved but don't tell how... and in the other case for example... what a program like yaourt do is called imperativ programming. shortly said.. begin on top of code and go to bottom with instruments like loops, functions, arrays etc.... here you tell how sth. can achieved... for this reason it MAYBE difficult to do what you want especially with a scripting language in my thought. i give no warranty for thd correctness of my rash thoughts. but when it is possible what you want i need to know how and why.... LEARNING NEVER STOP. and that is why i go from windows to linux. i love become more experienced.
i hope not all is wrong￼

maybe a idea is.... sth like yaourt...... - -noconfirm - -quiet puts you in the right direction.. oh just saw you wrote down the same idea... lool

sorry for my bad english￼

**Comment by rmarquis** [comment]
@maximbaz This is not possible in yaourt without a huge rewrite of the main code (think "throw away everything and start from scratch"). However, the alternative pacaur helper has been written with this specific workflow in mind. Bauerbill might also be worth a look.

**Comment by maximbaz** [comment]
Got it, thanks. Should I close the issue assuming it is never going to be implemented, or should I keep it open for tracking purposes waiting for someone brave to make this improvement?

**Comment by AladW** [comment]
Any change that's non-trivial will never be implemented in yaourt. If you like the interface, consider yay which is a rewrite in Go with an active maintainer.

https://github.com/Jguer/yay

**Comment by f2404** [comment]
As far as I can see, `yay` isn't an equal replacement. It doesn't support results sorting or custom output formatting. Having said that, the `yay` package takes 4 MB while `yaourt` and `package-query` together take less than 1 MB.
It doesn't seem like `yay` is mature enough.

**Comment by AladW** [comment]
If it doesn't support something that you want, mention it on the yay tracker. It won't get "mature" if people show no interest in helping the project. The 1 mb vs. 4 mb argument might be relevant if you're running Arch on a 1990's machine, except support for those was long dropped.

Of course, not that `yaourt` is a great example of a mature project - none of the basic issues present and reported since 2008 (split packages, arbitrary sourcing of PKGBUILDs, broken search output, broken dependency solving, exported variables that break the build process, proper RPC support, etc) were solved, nor will they ever be. `yay` dealt with those from day 1.

**Comment by maximbaz** [comment]
Among `pacaur` and `yay` the latter seems to be closer to the `yaourt`, I'll give it a longer try. Thank you all for the suggestions!
