### ISSUE TITLE
File conflict error check / post hooks not executed after a package failed

### ISSUE THREAD

**Issue by cinatic** [archlinuxfr/yaourt#329]
I always run into the same issue on my server. I am doing a system update "yaourt -Syu". kernel and other packages are updated but the package roundcube will throw some "existing file errors".
Ok so then i solve this existing file problem and reinstall roundcube, everything looks fine for me and i am going to reboot the server but it will not came up because the post install hook of linux package is not executed due to the errors.

Is there no such feature for checking of file conflicts like it is in pacman?

If there is for some reason not planned to do a file conflict check, maybe then hooks for the successfully installed packages should be executed

**Comment by f2404** [comment]
`yaourt` is calling `pacman` to actually install packages so there should be no differences.
Does roundcube package come from official repos or from AUR?

**Comment by cinatic** [comment]
okay i was not aware that yaourt just calls pacman. 

The package was from the official repo. I also raised an issue on bugtracker

https://bugs.archlinux.org/task/54239

**Comment by f2404** [comment]
Yes, `yaourt` is essentially a (huge) bash wrapper for `pacman` and `package-query`.
