### ISSUE TITLE
Caching git-repos 

### ISSUE THREAD

**Issue by sv1990** [archlinuxfr/yaourt#348]
It would be nice if yaourt would optionally save `*-git` packages somewhere other than `/tmp` so that it could run `git pull` rather than `git clone`. This would speedup download times especially for larger projects and also the build times since the unchanged object files could also be reused.
Of course the same could be done for other version control systems.

**Comment by humitos** [comment]
I've beeing looking for an option like this one for a couple of days and I just arrived at this issue. So, it seems that it doesn't exist yet. It would be awesome to have something like this.

I spend a lot more time downloading the source code than compiling it (besides, today I found `ccache` that helps on compiling time).

**Comment by harmathy** [comment]
Set `DEVELSRCDIR` in `yaourtrc` and git repos will be reused.

**Comment by sv1990** [comment]
@harmathy Thanks! That looks exactly like what I was searching for.
