### ISSUE TITLE
Unhandled exception with munged json data

### ISSUE THREAD

**Issue by rpdelaney** [archlinuxfr/yaourt#35]
```
$ yaourt -Ss fontforge
extra/fontforge 20140101-2
    Outline and bitmap font editor
lexical error: invalid char in json text.
                                       Error - Could not connect to AU
                     (right here) ------^
```

I can't reproduce this bug it so it may have been due to network issues. Nevertheless perhaps an exception handler is possible for when fetched json data can't be interpreted.

**Comment by Skunnyk** [comment]
It seems to be an error message from yajl…
And I can't reproduce.
