### ISSUE TITLE
no pager feature

### ISSUE THREAD

**Issue by albfan** [archlinuxfr/yaourt#354]
I recently updated to 1.9 and there's no --pager option anymore?

How is it supposed that one would look when there's more than one screen of results?

**Comment by f2404** [comment]
It doesn't seem to me that `--pager` has been removed...

**Comment by albfan** [comment]
Let me check again PKGBUILD

**Comment by albfan** [comment]
I use

    PAGER="less -R" yaourt --pager --color

Seems that without a package the message shown is 

    $ yaourt
    pacman: unrecognized option '--pager'

You can try with 

    $ yaourt --pager

while

    $ yaourt --pager foo

works, and

    $ yaourt --pager packagethatdonotexist

does not output anything

Let me see if I can fix that annoying message

**Comment by albfan** [comment]
Oh nevermind. it is trying to pass everything to pacman when do not recognize any command to yaourt
