### ISSUE TITLE
AUR comments aren't displayed anymore

### ISSUE THREAD

**Issue by Spike29** [archlinuxfr/yaourt#358]
Probably since the AUR 4.6.0 update, comments aren't displayed in Yaourt anymore.
Nicknames and timestamps are displayed, but not the comments themselves.

**Comment by f2404** [comment]
The comments seem to still be there for me...
```
$ yaourt -S yaourt-git

==> Downloading yaourt-git PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
Anonymous comment on 2013-04-03 11:41			 
thanks to make it works :)

ava1ar commented on 2014-03-10 03:25			 
git repo moved to https://github.com/archlinuxfr/yaourt, please update PKGBUILD
```

**Comment by Spike29** [comment]
Actually, I tried again and for some packages I see the comments, for some others I don't.
For example, I see yaourt and yaourt-git AUR comments, but not spotify ones.
