### ISSUE TITLE
Could read package lists from files

### ISSUE THREAD

**Issue by es20490446e** [archlinuxfr/yaourt#365]
It would be quite useful if yaourt could have as argument not only package names, but also plain text files which contained list of packages.

This way one could have a list of packages to install, and just pass the text file as argument to perform an instant installation of a hole system.

This would allow installing OEM and enterprise computers almost instantly, or reinstalling a faulty system with very little downtime.

**Comment by germeuser** [comment]
Can't you just use nested shell commands for this?
`yaourt -S $(cat package-list.txt)`

**Comment by es20490446e** [comment]
I would rather write a tool myself. Thank you ;)
