### ISSUE TITLE
Add options for "man in the middle attack"

### ISSUE THREAD

**Issue by dracorp** [archlinuxfr/yaourt#366]
Hi there
In my company we have decrypted https traffic. So I added proper CA cert to /etc/ca-certificates/trust-source/anchors and also added -k switch to ~/.curlrc but yaourt does not work:
```
curl error: Peer certificate cannot be authenticated with given CA certificates
```
I had to modify /usr/lib/yaourt/util.sh and I added **--insecure** option to pkgquery function.

Best regards, Piotr

**Comment by f2404** [comment]
Er, according to the [man](https://github.com/archlinuxfr/yaourt/blob/8b7b86f406630c42658bac8e132af270e8a8856f/src/man/yaourt.8#L121), there's support for `--insecure` option already. Doesn't it work?

**Comment by dracorp** [comment]
Hmm, I'll check this. I've missed that.

**Comment by dracorp** [comment]
Yes, it works. I'll create alias for it. But in my opinion it'd more elegant if there was an option for it in /etc/yaourtrc.

**Comment by f2404** [comment]
Well, I agree. You're welcome to implement the option ;)
