### ISSUE TITLE
"Continue building" prompt error on translation

### ISSUE THREAD

**Issue by shortlisted** [archlinuxfr/yaourt#369]
The "continue building" prompt is translated to swedish:

```
==> Fortsätta bygga command-not-found ?[J/n]
==> ----------------------------------------
==> J

```
The build will cancel on anything that isn't Y, so picking J (or j) for swedish yes (Ja) cancels the build.

![2018-03-14-210625_801x452_scrot](https://user-images.githubusercontent.com/14911221/37428498-b63cc578-27cc-11e8-992a-0b6bfcc0ee27.png)

J/n selection does work for the earlier options.

**Comment by larchunix** [comment]
Hi,

This should be fixed by https://github.com/archlinuxfr/yaourt/commit/fe1bcdd8610230bb75289f4b4c43607346ad18a9#diff-1567facf6c6fe6f7f4a4e7cb0c7a29ceL385
