### ISSUE TITLE
【i18n】【zh_CN】【Ambiguity】

### ISSUE THREAD

**Issue by DCjanus** [archlinuxfr/yaourt#375]
With command like `LANGUAGE=en_US.UTF8 yaourt -Syyua`, last line of output is `No database errors have been found!`

With command like `LANGUAGE=zh_CN.UTF8 yaourt -Syyua`, last line of output is `找不到数据库错误！`.

There is ambiguity in this sentence, It could be `找不到 数据库错误` ( `No database errors have been found!` ) or `找不到数据库 错误` ( `Here's an error called 'No database' found` )

**Comment by f2404** [comment]
Hi, this isn't a yaourt's string, it's from pacman - see https://git.archlinux.org/pacman.git/tree/src/pacman/po/zh_CN.po#n522

I guess you'd need to file a bug against their translation or somehow fix it.
