### ISSUE TITLE
/usr/lib/yaourt/pacman.sh: line 18:  : command not found -- (only in zsh)

### ISSUE THREAD

**Issue by izilly** [archlinuxfr/yaourt#41]
When running yaourt from zsh, it fails when running commands that install aur packages.  I thought it might be caused by something in my .zshrc/.zshenv, but running zsh with the NO_RCS option had no effect.  Example:

    $ zsh -f -c 'yaourt gcalcli'
    /usr/lib/yaourt/pacman.sh: line 18:  : command not found
    1 aur/gcalcli 2.4.2-1 (109)
        Google Calendar Command Line Interface
    2 aur/gcalcli-git 20130415-1 (12)
        Allows you to access you Google Calendar from a command line, git version
    ==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
    ==> -------------------------------------------------------
    ==> 1

    error: database not found: aur

The same command works fine if run from a bash shell.  The error arises from the following lines from pacman.sh:

	eval $(pacman_parse --debug -T |&
	  sed -n -e 's/"/\\"/g' \
             -e 's/^[\[\]0-9: ]//' \
             -e 's/^debug: config: \([a-zA-Z]\+\): \(.*\)/P[\1]="${P[\1]}\2 "/p' \
             -e 's/^debug: config: \([a-zA-Z]\+\)$/P[\1]=1/p' \
             -e "s/^debug: option '\([a-zA-Z]\+\)' = \(.*\)/P[\1]=\"\2\"/p"
	)

I gather the command substitution is spawning a subshell that runs in zsh and produces (almost) blank output.  I temporarily changed `eval` to `echo` and ran it again in zsh and bash.  In zsh it outputs:

    " " " " " "

bash output:

    P[HoldPkg]="${P[HoldPkg]}pacman " P[HoldPkg]="${P[HoldPkg]}glibc " 
    P[arch]="${P[arch]}x86_64 " P[totaldownload]=1 P[verbosepkglists]=1 
    P[SigLevel]="${P[SigLevel]}Required " 
    P[SigLevel]="${P[SigLevel]}DatabaseOptional " 
    P[LocalFileSigLevel]="${P[LocalFileSigLevel]}Optional " 
    P[logfile]="/var/log/pacman.log" P[gpgdir]="/etc/pacman.d/gnupg/" 
    P[cachedir]="/var/cache/pacman/pkg/"

I'm not sure why those sed commands don't work in zsh, something to do with quoting/escaping I guess.  I'm working around it for now by sourcing a function in my .zshrc that overrides the yaourt command:

    yaourt () {
            bash -c "yaourt $@"
    }

**Comment by tuxce** [comment]
Sorry for the late reaction.
I cannot reproduce this, and I don't understand how zsh can influence another process.
I tried to run this command in a zsh session, it gave me the right output.

Maybe you have set $PACMAN to something else on zsh ? or a different $PATH with another `pacman` command ?
Did `pacman -T --debug` gives you the same output on zsh and bash ?

**Comment by Skunnyk** [comment]
I did not manage to reproduce. Do you still have the problem ?
