### ISSUE TITLE
stats should handle optional deps

### ISSUE THREAD

**Issue by mattia-b89** [archlinuxfr/yaourt#44]
If i execute:
yaourt --stats

the entry "packages no more used by any package" it's wrong because doesn't keep in mind optional dependencies

e.g.: I have meld which has "pygtksourceview2" as optional dependency
but pygtksourceview2 is listed as package that is no more used by any package

**Comment by tuxce** [comment]
pacman 4.2 changes the behavior of --unrequired options, now, only real unrequired are displayed.

**Comment by mattia-b89** [comment]
perfect
