### ISSUE TITLE
stats 

### ISSUE THREAD

**Issue by mattia-b89** [archlinuxfr/yaourt#46]
yaourt --stats when try to find for no more used packages doesn't handle dependencies for unsupported installed packages.

e.g.: I have "python2-setproctitle" from AUR which was an optional deps for kupfer.
if I uninstall kupfer yaourt --stats doesn't show me "python2-setproctitle" as unused package

**Comment by tuxce** [comment]
Actually, packages installed locally are treated equally even if you install some of them from unsupported repository or from AUR.
If you still can reproduce this case, can you check if `pacman -Qi python2-setproctitle` have a package in *Optional For* line ?

**Comment by mattia-b89** [comment]
I still have this issue

[mattia@arch-desktop ~]$ pacman -Qi python2-setproctitle
Name           : python2-setproctitle
Version        : 1.1.8-1
Description    : allows a python process to change its process title
Architecture   : x86_64
URL            : http://code.google.com/p/py-setproctitle/
Licences       : BSD
Groups         : None
Provides       : None
Depends On     : python2
Optional Deps  : None
Required By    : None
Optional For   : kupfer
Conflicts With : None
Replaces       : None
Installed Size :  24.00 KiB
Packager       : mattia.b89 <mattia.b89@gmail.com>
Build Date     : Tue 13 Jan 2015 22:28:30 CET
Install Date   : Tue 13 Jan 2015 22:28:32 CET
Install Reason : Explicitly installed
Install Script : No
Validated By   : None

**Comment by tuxce** [comment]
This package was explicitly installed, it is not considered as a dependency.
To set it as a dependency : `pacman -D --asdeps python2-setproctitle`
After that, if you remove kupfer, `yaourt --stats`should display it as an unused package.

**Comment by mattia-b89** [comment]
ok, perfect!
but now I'm confused: how can be an optional dependebcy installed automatically as dependency?

**Comment by tuxce** [comment]
For now, you can't (https://bugs.archlinux.org/task/11337)

**Comment by mattia-b89** [comment]
ok, thank you.
I commente the archlinux bug issue aforementioned by you, sharing my experience on this "problem"
