### ISSUE TITLE
Unnecessary root warning

### ISSUE THREAD

**Issue by exuvo** [archlinuxfr/yaourt#48]
The "fix" for #13 in ec38666 is silly. There is no need to print a warning message about 'building as root' and delay for 2 secs when installing normal packages or querying the local database.
That warning is only relevant for when actually building packages and most operations already have a 'wait for keypress' before actually proceeding.

 I request a revert of ec38666

**Comment by tuxce** [comment]
The warning was removed, but --asroot had been dropped -> #67
