### ISSUE TITLE
yaourt asking for both user and root password 

### ISSUE THREAD

**Issue by Narthorn** [archlinuxfr/yaourt#5]
Just a heads-up : as of [sudo 1.8.10](http://www.sudo.ws/sudo/devel.html#1.8.10b1), sudo -l will always prompt for the user password.

For people with targetpw/rootpw/runaspw options in their sudoers file, this means that they now have to type in two passwords instead of one.

By itself, this would only be mildly annoying, but combined with [sudo bug 639](http://www.sudo.ws/bugs/show_bug.cgi?id=639) which makes sudo -l ask for the password of the wrong user, it results in this very very confusing scenario :

```
└─[$] yaourt -Syua
[sudo] password for root:   # now asking for root password
[sudo] password for root:   # actually asking for user password
:: Synchronizing package databases...
```

In any case, yaourt should no longer use "sudo -l command" before running the actual command so that users of targetpw do not have to enter both root password and their own password.

In the meantime, SUDONOVERIF=1 in .yaourtrc will work as a quick fix.

**Comment by utack** [comment]
Will this ever change?
