### ISSUE TITLE
All packages made in split PKGBUILD

### ISSUE THREAD

**Issue by Mikayex** [archlinuxfr/yaourt#50]
When installing a subpackage (transmission-sequential-cli) from a split PKGBUILD, yaourt build and install all packages (`yaourt -S transmission-sequential-cli`).

However when I do `yaourt --pkg transmission-sequential-cli -S transmission-sequential-cli`, yaourt build/install only the requested package (since it's passing the `--pkg transmission-sequential-cli` option to makepkg).

I think the default behavior should be to build/install only the requested package when it's a split PKGBIULD, which mean pass the `--pkg` option to makepkg

**Comment by Skunnyk** [comment]
Pull request https://github.com/archlinuxfr/yaourt/pull/65 should fix this issue
