### ISSUE TITLE
Hidden Prompt For Fingerprint Sudo Auth

### ISSUE THREAD

**Issue by silverhammermba** [archlinuxfr/yaourt#53]
I have my fingerprint reader set up to authenticate for sudo (using [fprint](https://wiki.archlinux.org/index.php/Fprint)), which works fine. But when yaourt needs sudo permission, it does not show the fingerprint reader prompt - which makes it look like it is hanging. If I swipe my finger, it authenticates just fine so it is really just the prompt that is hidden.

If I don't swipe, eventually the fingerprint reader times out and yaourt shows the regular sudo password prompt.

**Comment by tuxce** [comment]
Set `SUDOREDIRECT=0` in `/etc/yaourtrc` or `$HOME/.yaourtrc`
