### ISSUE TITLE
EXPORTDIR should not be used for SRCDEST

### ISSUE THREAD

**Issue by mkoskar** [archlinuxfr/yaourt#59]
From documentation it is not clear that `yaourt` will in fact use `EXPORTDIR` for `SRCDEST`.

By setting `EXPORTDIR` one would expect `PKGDEST` and `SRCPKGDEST` overridden but not `SRCDEST`. It doesn't make sense to mix sources with packages, and source packages, not mentioning that the sources are already inside source packages.

Setting `EXPORTSRC=0` doesn't disable exporting of sources (or in fact setting `SRCDEST`) it only doesn't export resulting source package (or rather doesn't generate it at all).

I think it would be more consistent and logical to keep `SRCDEST` as is set by `makepkg`.

**Comment by tuxce** [comment]
`EXPORTDIR` was added before the creation of `SRCPKGDEST` and was used to set both `PKGDEST` and `SRCDEST`.

makepkg `*DEST` var can be set in `/etc/yaourtrc` or `$HOME/.yaourtrc` if you want.
