### ISSUE TITLE
Cannot use pacmatic as PACMAN

### ISSUE THREAD

**Issue by hetraeus** [archlinuxfr/yaourt#69]
Hello, if I set PACMAN variable to "pacmatic" it does not work. I tried it changing the variable in /etc/yaourtrc and passing PACMAN=pacmatic in both zsh and bash. I even tried to pass PACMAN=ls just to see if something would break but still nothing: yaourt is ignoring PACMAN.

**Comment by Skunnyk** [comment]
Works for me : 
> $ PACMAN="pacmatic" yaourt -Syu

Give me : 
> 8218 pts/4    S+     0:00  |   \_ /bin/bash /usr/bin/yaourt -Syu
> 8240 pts/4    S+     0:00  |       \_ sudo pacmatic --color auto -Sy
> 8241 pts/4    S+     0:00  |           \_ /bin/bash /usr/bin/pacmatic --color auto -Sy
> 8263 pts/4    S+     0:00  |               \_ pacman --color auto -Sy
 
And :
> PACMAN="ls" yaourt -Syu      
> ls: invalid option -- 'y'
> Try 'ls --help' for more information.

**Comment by tuxce** [comment]
Works for me too
