### ISSUE TITLE
yaourt keeps reporting a package as upgradable

### ISSUE THREAD

**Issue by Xwang1976** [archlinuxfr/yaourt#77]
On my archlinux system yaourt keeps reporting an AUR  package as upgradable whereas it is already updated.
These are the two commands which highlight the problem:

yaourt -Syu --aur
:: Sincronizzazione dei database in corso...
core è aggiornato
extra è aggiornato
community è aggiornato
multilib è aggiornato
pipelight è aggiornato
sundials : Orfano
Altri pacchetti: - 66 / 66

yaourt -Qua
aur/openfoam 2.3.1-2

So the package openfoam is already updated but appears yaourt -Qua reports it and yaourt -Syu --aur do not upgrade it (it is already updated).

**Comment by tuxce** [comment]
Can you provide the output of the following commands :
`package-query -Auf '%s/%n %l %v'`
and after a system upgrade :
`package-query -QAuf '%s/%n %l %v'`

**Comment by Xwang1976** [comment]
Konsole output
package-query -Auf '%s/%n %l %v'
aur/openfoam 2.3.1-2 2.3.1-2

sudo pacman -Syu

:: Sincronizzazione dei database in corso...
core è aggiornato
extra è aggiornato
community è aggiornato
multilib è aggiornato
pipelight è aggiornato
:: Aggiornamento del sistema in corso...
non ci sono aggiornamenti disponibili

sudo yaourt -Syu --aur
==> ATTENZIONE: Compilare pacchetti con privilegi di root è pericoloso.
Esegui yaourt come utente non privilegiato.
::Sincronizzazione dei database in corso...
core è aggiornato
extra è aggiornato
community è aggiornato
multilib è aggiornato
pipelight è aggiornato
Altri pacchetti: - 66 / 66

package-query -QAuf '%s/%n %l %v'
aur/openfoam 2.3.1-2 2.3.1-2

**Comment by tuxce** [comment]
AUR reports `"2.3.1-2 "` (with a space at the end : https://aur.archlinux.org/rpc.php?type=info&arg=openfoam)
So the comparison returns `"2.3.1-2 "` > `"2.3.1-2"` 
For now, I don't know if it's a package error or AUR rpc's error.

**Comment by Xwang1976** [comment]
Solved. It was a package error.
Thank you very much.
