### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by prescott66** [archlinuxfr/yaourt#79]
I have problem with translating [Y/n] and "A" for Abort.
Because in slovak language is [Y/n] = [A/n]  so   there is a mismatch with "A" for abort.
How should i translate this?
Should i keep [Y/n] in translation ?

It would be nice, if can be in my language changed "A" (Abort) to "P" because "Abort" is translated to "Prerušiť".

**Comment by tuxce** [comment]
I don't see the problem.
In addition to `[Y/n]`, you have to translate the sentence 191 (`("A" for Abort)`) to `("P" xxx Prerušiť)` and sentence 192 (`YNA`) to `ANP`.

**Comment by prescott66** [comment]
got it!
thanks for your help!
