### ISSUE TITLE
Revive Transifex project

### ISSUE THREAD

**Issue by skybon** [archlinuxfr/yaourt#81]
We have to move translations back to GMS platform or .po files will slowly drift out of sync with each upgrade and contributing will be problematic.

Manual translation maintenance is generally a no-go.

**Comment by Skunnyk** [comment]
Yaourt translation is available on https://www.transifex.com/projects/p/yaourt/ .
I'm agree, we must take care of this part, I need to read some transifex documentation to setup a sync I guess. If you have some tips, you're welcome.

**Comment by Skunnyk** [comment]
See https://github.com/archlinuxfr/yaourt/commit/5a641806df0e739ea4ada69df2d9dd3eec4eeb15 and https://github.com/archlinuxfr/yaourt/commit/c929b2d22c62d79d6ee69f8dffe710883da5251a
