### ISSUE TITLE
Support for regex when searching AUR packages?

### ISSUE THREAD

**Issue by InfernoZeus** [archlinuxfr/yaourt#82]
As far as I can tell, Yaourt doesn't support regex when searching AUR packages. Is this correct? Example log which seems to indicate this:

```
> yaourt skype
....
31 aur/skype4pidgin-svn 665-2 (402)
    A Skype plugin for libpurple clients (Pidgin, Empathy, Finch, etc)
32 aur/skype4py 1.0.35-1 (52)
    Python wrapper for the Skype API
33 aur/skype4py-git 1.0.35.r7.g8d59590-1 (12)
    Python wrapper for the Skype API
34 aur/skype_oss_wrapper-git r16.ad9f1d8-2 (1)
    A fake libpulse.so library that mimics pulseaudio behavior for skype, instead redirecting it to OSSv4
35 aur/skypetab-ng-git v0.5.0.fixed.25.g949a7c1-1 (49)
    A program that adds tabs to Skype™ for Linux
36 aur/tox-git r3114.gb7e0033-1 (110)
    A FOSS instant messaging application aimed to replace Skype (git version)
37 aur/tox-qt-git 1:0.1.0.r382.g102a776-1 (35)
    FOSS instant messaging application aimed to replace Skype (GUI) (Git version)
38 aur/toxic-git 0.5.2.r33.gd26c8fe-1 (27)
    CLI client for tox, a Skype replacement that respects your privacy
....

> yaourt ^skype
1 community/skype-call-recorder 0.9-1
    Open source tool that allows you to record your Skype calls on Linux
2 multilib/skype 4.3.0.37-3 [installed]
    P2P software for high-quality voice communication
```
As you can see, there are packages in AUR which should match that regex, but they aren't being listed.

Support for this would be pretty useful. Is it something that should be raised against package-query though?

**Comment by larchunix** [comment]
As you guessed, yaourt delegate the search to package-query:

    > package-query --aur-url https://aur.archlinux.org -S -A -s -- 'skype'
    
    > package-query --aur-url https://aur.archlinux.org -S -A -s -- '^skype'

You should report this to package-query.

**Comment by Skunnyk** [comment]
Yup, search is handled by package-query, using https://aur.archlinux.org/rpc.php .
 I don't see any possibility to search by regex on aurjson though.
