### ISSUE TITLE
Show a diff (colored? ♥) of the PKGBUILD instead of just the new one

### ISSUE THREAD

**Issue by michalrus** [archlinuxfr/yaourt#83]
It would be soooooooooooo much faster to judge malice of the PKDBUILDs of packages being updated if we were shown the *full diff* between the old one and the new one.

I’d argue, it would be much more secure, too. See:

![pkgbuild diff screenshot](http://i.imgur.com/K1JopKD.png)

If I see something like that, I know that only upstream changed, PKGBUILD itself is intact.

**Comment by jrakoczy** [comment]
Big :+1: to this.

**Comment by Skunnyk** [comment]
It will be possible with AUR4 has PKGBUILD will be stored in git. 
But it need some yaourt works, so patch are welcome :)

**Comment by michalrus** [comment]
@Skunnyk, that’s really great. :heart:

**Comment by Skunnyk** [comment]
Now that yaourt support git clone when downloading PKGBUILD from AUR ( #142), maybe we can implement it 
- Something like git diff HEAD~1 HEAD~0 ?
- Be aware if only 1 revision
- How to choose from which revision we need to diff ? Multiples commits, multiples revisions etc
- etc

**Comment by michalrus** [comment]
@Skunnyk, comparing the last two revisions would be a decent *fallback* if the below didn’t work (when wouldn’t it? I dunno).

However, it would be way cooler for yaourt to get currently installed `$pkgver` of the package, then find the revision of the `PKGBUILD` in which the version was set to the version currently installed and compare *this* revision with `HEAD`.

**Comment by yan12125** [comment]
The approach proposed by @michalrus may fail in some cases:
1. CVS packages
2. Packages that we've edited PKGBUILD on the fly.

Maybe storing the final PKGBUILD of a build somewhere is an option?

**Comment by Skunnyk** [comment]
@michalrus : there is no way to know which commit correspond to which release. See https://aur.archlinux.org/cgit/aur.git/log/?h=squeeze-git for example, how to know ? :)

@yan12125 : CVS packages ? AUR run on git !
I don't want to over complicate yaourt code. Store all pkgbuilds is not an option for me :]


However, patchs are welcome :)

**Comment by michalrus** [comment]
@Skunnyk, what do you mean? Take a look at the quick hack below. Lists `$pkgver` for each git revision reachable from `master`. Really simple, but you can elaborate from here.

```
% git clone https://aur.archlinux.org/squeeze-git.git
Cloning into 'squeeze-git'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 16 (delta 5), reused 11 (delta 1)
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.

% cd squeeze-git 

% git rev-list master | while read rev ; do echo $rev: ; git show $rev:PKGBUILD | grep pkgver= ; echo ; done
b716d9f202d40467dd98af5b13892d3008704d54:
pkgver=0.4.90git.r1034.12f4d28

070177dcaa06a3aad9cccaa110f399f838e2d5d3:
pkgver=0.4.90git.r1032.af38709

e17ed8e99bca4864996b46ce84608596694dc455:
pkgver=0.4.90git.r1030.d84b736

f77f7fe77ee17c6ecea67730cb74faeaff5410d1:
pkgver=0.4.90git.r1030.d84b736

%
```

@yan12125, CVS? Aren’t all `PKGBUILD`s of packages in AUR version-controlled by git?

**Comment by yan12125** [comment]
Sorry I misspelled. VCS is correct. I mean packages like freerdp-git or llvm-svn. ```$pkgver``` is modified by ```makepkg``` when building unless ```--holdver``` is specified. For such packages, it's likely that the actual package version is not found in any commit of the git repo.

**Comment by f2404** [comment]
Has this issue been resolved?

**Comment by larchunix** [comment]
This feature has been added with #202.

It should work in git version of yaourt by setting `AURUSEGIT` and `AURSHOWDIFF` to `1` in `yaourtrc`.
