### ISSUE TITLE
Cannot install from the repo, missing archlinuxfr.db file.

### ISSUE THREAD

**Issue by Poincare1** [archlinuxfr/yaourt#84]
I added the repo as listed in the yaourt wiki page here: https://archlinux.fr/yaourt-en  

I then cannot add yaourt, even after pacman -Syu.  :(

Here is the output stating a missing archlinuxfr.db file ... 

# pacman -Sy yaourt
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
error: failed retrieving file 'archlinuxfr.db' from repo.archlinux.fr : The requested URL returned error: 404
error: failed to update archlinuxfr (unexpected error)
error: target not found: yaourt

If it will help, here is my uname output:

$ uname -a
Linux alarm 3.10.69-1-ARCH #1 SMP PREEMPT Sat Feb 14 09:51:55 MST 2015 armv7l GNU/Linux

**Comment by luluone** [comment]
Adding "Server = http://repo.archlinux.fr/arm" instead of "/$arch" to  /etc/pacman.conf works for me.
But you have to install package-query first for yaourt 
curl -O https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
tar zxvf package-query.tar.gz
cd package-query
makepkg -si
