### ISSUE TITLE
==> ERROR: ... not found in AUR.

### ISSUE THREAD

**Issue by zoof** [archlinuxfr/yaourt#86]
I have been getting these errors for several weeks now and I believe it has something to do with SSL since "yaourt -S --insecure <pkgname>" works but "yaourt -S <pkgname>" does not.  Is there some way to turn on debugging so that I can isolate the origin of this problem?

**Comment by Skunnyk** [comment]
Do you have a way to reproduce the problem ? never seend an ssl problem here
You can run "bash -x yaourt" to have an "debug" output. (but maybe the problem is on package-query side)

**Comment by zoof** [comment]
Thank you very much!  I have isolated to problem to be the result of prepending $HOME/anaconda/bin to my PATH.  The Anaconda Python distribution comes with its own version of various libraries including curl and openssl so one of these libraries is not playing nice with yaourt.  I shall have to think of an alternative method for executing my python scripts.

**Comment by zoof** [comment]
Just to follow up on this, I have isolated the problem to be the version of curl packaged with Anaconda.  Is there some way to specify that yaourt should use /usr/bin/curl?

**Comment by heat-wave** [comment]
I seem to have found out how to resolve this. Anaconda's curl has troubles when working with https, so that might be the reason why yaourt can't install anything. The command "conda remove curl" leaves you with normal version of curl, and yaourt starts to work properly. I haven't yet checked if Anaconda works after having its curl deinstalled, though.

**Comment by zoof** [comment]
Many thanks!  conda still seems to work after uninstalling curl.
Haven't tried anything else that might use curl.

**Comment by kairuku** [comment]
I just upgraded yaourt to 1.6-1 and experimented with uncommenting the AURURL line in /etc/yaourtrc to reflect aur4, and tried to update a package that I know is on aur4 but not aur. I got this same `not found in AUR` error, and I've never had Anaconda installed. Moreover, which curl yields `/usr/bin/curl`.

I've never had this error prior to now.

**Comment by Skunnyk** [comment]
@kairuku : I think your problem is related to https://github.com/archlinuxfr/package-query/issues/8 (related to AUR4 rpc api change).
Can you try with package-query-git ? I'll release a new package-query version soon.

**Comment by kairuku** [comment]
@Skunnyk: I uninstalled package-query and yaourt and reinstalled manually from aur4 and the error message has gone away, and I was also able to install the aur4 package that had been problematic earlier. Thank you for releasing a new version so quickly :)

**Comment by rvu95** [comment]
could you give me more information how to get rid of this error without uninstalling anaconda?

**Comment by heat-wave** [comment]
@rvu95 you don't have to uninstall the entire anaconda, just removing curl from the anaconda package has done the trick for me.

**Comment by rvu95** [comment]
ah, okay, thanks.

**Comment by mmrezaie** [comment]
Thanks. "conda remove  curl" works. Although I am not sure what is going to break in anaconda.

**Comment by zoof** [comment]
My experience is that nothing in anaconda gets broken.  I surmise that curl is included with anaconda in case one's linux distribution does not come preinstalled with curl.

**Comment by synchro--** [comment]
Thank you @heat-wave. For the records, I had a problem with 
`pacaur can't connect to the AUR` while cower works fine. Since I hadn't found anything meaningful wrt pacaur, I searched the yaourt issues and discovered this solution that fixed also my pacaur problem.
