### ISSUE TITLE
Mention -A and MAKEPKG_ARG in man page

### ISSUE THREAD

**Issue by pezz** [archlinuxfr/yaourt#89]
There's some nice undocumented features of yaourt (related to makepkg) that are real handy when using it on Arch Linux ARM -- namely the -A argument or the MAKEPKG_ARG rc option.

It's very useful to be able to override the arch array of a PKGBUILD when using this distro of Arch on a Pi etc.

It'd be nice if the man page for yaourt could be updated to mention these options.

I realise that the option is part of makepkg, but it's not immediately obvious to some users of yaourt on how to control this.

Cheers.

**Comment by larchunix** [comment]
MAKEPKG_ARG variable should probably stay private. Instead, the variable MAKEPKG which has been introduced (1997977) and documented (d6203ee) should be used to add custom options to makepkg.
